/* Official Production reception. Public identifiers only; runtime CREATE_ENABLED remains the server-side release/rollback gate. */
(()=>{'use strict';
window.ASOBOON_V2_ENV=Object.freeze({
  environment:'production',
  environmentLabel:'OFFICIAL',
  storageNamespace:'production',
  channelId:'2009884613',
  liffId:'2009884613-ELc6kolf',
  liffUrl:'https://miniapp.line.me/2009884613-ELc6kolf',
  endpoint:'https://asoboon.github.io/asoboon-stamp/miniapp-v2/production/',
  assetBase:'https://asoboon.github.io/asoboon-stamp/miniapp-v2/production/',
  siteBase:'https://asoboon.github.io/asoboon-stamp/',
  backendUrl:'https://asoboon-miniapp-v2-production-gateway.asoboon425.workers.dev/',
  backendEnvironment:'official-production',
  lineStoreOnly:true,
  officialHome:true,
  operationalFallbacks:Object.freeze({
    enabled:false,
    receptionUrl:'https://airwait.jp/WCSP/storeDetail?storeNo=AKR2298124918',
    callstatusUrl:'../../callstatus.html'
  }),
  featureFlags:Object.freeze({
    reception:true,
    receptionCreate:true,
    callstatus:true,
    serviceMessage:true,
    timeguide:true,
    firstGuide:true,
    entryGuide:true,
    rules:true,
    stamp:false,
    omikuji:false,
    game:false,
    parking:true
  })
});
})();
