/* ASOBooN Model public configuration. Never put API keys or staff secrets here. */
window.QUEUE_PRODUCT_CONFIG = Object.freeze({
  productVersion: 'ASOBooN-1.0.0-rc1',
  demoMode: new URLSearchParams(location.search).get('demo') === '1',
  brandName: 'ASOBooN',
  backendUrl: 'https://script.google.com/macros/s/REPLACE_WITH_ASOBOON_BACKEND/exec',
  homeUrl: '../../../home.html',
  callStatusUrl: '../../../yobidashi.html',
  locale: 'ja-JP',
  timezone: 'Asia/Tokyo',
  staffKeyStorageKey: 'asoboon_model_staff_key',
  requestTimeoutMs: 10000,
  mutationPollMs: 650,
  mutationMaxPolls: 14,
  receptionCloseHour: 18,
  nextDayOpenHour: 19,
  maxTotalPeople: 10,
  childrenPerAdult: 3,
  priceAdult: 600,
  priceChild: 900,
  waiverText: 'ASOBooNの利用ルールとスタッフの案内に従ってご利用ください。安全のため、保護者の方はお子さまから目を離さないようお願いいたします。',
  blockedWaitTypeIds: ['0042'],
  blockedNamePatterns: ['WEB','テスト','ご待機者専用','待機者専用'],
  staffRefreshMs: 10000,
  serverAuto: true,
  autoCallingPool: 10,
  autoStopTime: '18:00',
  slotStartOverrides: new URLSearchParams(location.search).get('demo') === '1' ? {D101:'00:00',D102:'23:59'} : {}
});
