(()=>{'use strict';
const SETTINGS=Object.freeze({CAPACITY:350,CROWD_BASE:310,LEVELS:Object.freeze([{max:39,label:'空いています'},{max:59,label:'比較的空いています'},{max:79,label:'やや混雑'},{max:94,label:'混雑しています'},{max:100,label:'かなり混雑しています'}])});
const frame=document.getElementById('miniappCore'),params=new URLSearchParams(location.search);
const coreUrl=new URL('./home-core.html',location.href),callUrl=new URL('./callstatus-purple.html?v=20260921-1',location.href).href;
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function count(v){if(typeof v!=='string'&&!Number.isInteger(v))return null;const raw=String(v);if(!/^\d+$/.test(raw))return null;const n=Number(raw);return Number.isSafeInteger(n)&&n<=SETTINGS.CAPACITY?n:null}
function metrics(value){const remaining=count(value);if(remaining===null)return null;const current=Math.max(SETTINGS.CAPACITY-remaining,0);const percent=Math.min(100,Math.floor(current/SETTINGS.CROWD_BASE*100));return{percent,remaining,level:SETTINGS.LEVELS.find(x=>percent<=x.max).label}}
function acceptance(slot,m){if(slot.closed===true)return{kind:'closed',label:'受付終了'};if(m.remaining===0)return{kind:'full',label:'満員'};return{kind:'open',label:'受付中'}}
function card(slot){const m=metrics(slot.remaining),name=String(slot.label||'対象回');if(!m)return'';const a=acceptance(slot,m);const remaining=a.kind==='closed'?'':`<div class="purple-crowd-counts"><span>受付残り <strong>${m.remaining.toLocaleString('ja-JP')}名</strong></span></div>`;return `<article class="purple-crowd-card ${a.kind}"><header><strong>${esc(name)}</strong><span>${a.label}</span></header><div class="purple-crowd-main"><small>混雑目安</small><b>${m.percent}<i>%</i></b><em>${m.level}</em></div><div class="purple-crowd-track" role="progressbar" aria-label="${esc(name)}の混雑目安" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${m.percent}"><span style="width:${m.percent}%"></span></div>${remaining}</article>`}
function ensureStyle(doc){if(doc.getElementById('purpleCrowdStyle'))return;const s=doc.createElement('style');s.id='purpleCrowdStyle';s.textContent=`.purple-crowd{margin:12px 0;padding:15px;border:2px solid #cab0df;border-radius:20px;background:linear-gradient(180deg,#fff,#f6effc);box-shadow:0 8px 20px rgba(73,32,112,.1);font-family:-apple-system,BlinkMacSystemFont,"Hiragino Sans","Yu Gothic",sans-serif}.purple-crowd>h2{margin:0;color:#472269;font-size:20px}.purple-crowd>p{margin:5px 0 0;color:#655372;font-size:13px;line-height:1.45}.purple-crowd-list{display:grid;gap:10px;margin-top:12px}.purple-crowd-card{padding:13px;border:1px solid #d9cbe4;border-radius:16px;background:#fff}.purple-crowd-card header{display:flex;align-items:center;justify-content:space-between;gap:8px}.purple-crowd-card header>strong{color:#302538;font-size:16px}.purple-crowd-card header>span{flex:none;padding:5px 8px;border-radius:999px;background:#e9f4ed;color:#23613d;font-size:12px;font-weight:900}.purple-crowd-card.closed header>span{background:#eee;color:#555}.purple-crowd-card.full header>span{background:#f5e8e6;color:#843d35}.purple-crowd-main{display:grid;grid-template-columns:auto 1fr;align-items:end;column-gap:10px;margin-top:9px}.purple-crowd-main small{color:#67457d;font-size:13px;font-weight:800}.purple-crowd-main b{grid-row:1/3;color:#572582;font-size:44px;line-height:.9;text-align:right;letter-spacing:-.05em}.purple-crowd-main b i{font-size:19px;font-style:normal}.purple-crowd-main em{color:#594862;font-size:14px;font-style:normal;font-weight:800}.purple-crowd-track{height:12px;margin-top:10px;overflow:hidden;border-radius:99px;background:#e7e0eb}.purple-crowd-track span{display:block;height:100%;border-radius:inherit;background:linear-gradient(90deg,#4c83aa,#7650a4)}.purple-crowd-counts{margin-top:10px}.purple-crowd-counts span{display:block;padding:9px;border-radius:11px;background:#f4eff7;color:#5e5265;font-size:13px}.purple-crowd-counts strong{margin-left:8px;color:#572582;font-size:20px}.purple-crowd-error{margin-top:12px;padding:14px;border-radius:14px;background:#f0edef;color:#4f4753;font-size:14px;font-weight:800}.purple-crowd-demo{display:inline-flex;margin-top:8px;padding:4px 7px;border-radius:7px;background:#6a35a8;color:#fff;font-size:12px;font-weight:900}@media(max-width:360px){.purple-crowd{padding:12px}.purple-crowd-main b{font-size:40px}}`;doc.head.appendChild(s)}
function ensurePanel(doc){let panel=doc.getElementById('purpleCrowdPanel');if(panel)return panel;panel=doc.createElement('section');panel.id='purpleCrowdPanel';panel.className='purple-crowd';panel.innerHTML='<h2>本日の混雑状況</h2><p>受付状況をもとにした目安です。館内の滞在人数ではありません。</p><div class="purple-crowd-list"></div>';const home=doc.querySelector('#homeView .home-shell'),anchor=home?.querySelector('.route-guide');if(anchor)anchor.insertAdjacentElement('beforebegin',panel);else home?.appendChild(panel);return panel}
function render(slots,{demo=false}={}){const doc=frame.contentDocument;if(!doc)return;ensureStyle(doc);const panel=ensurePanel(doc),list=panel?.querySelector('.purple-crowd-list');if(!list)return;const valid=(Array.isArray(slots)?slots:[]).filter(x=>metrics(x?.remaining));list.innerHTML=valid.length?valid.map(card).join(''):'<div class="purple-crowd-error">混雑情報を取得できません</div>';let badge=panel.querySelector('.purple-crowd-demo');if(demo&&!badge){badge=doc.createElement('span');badge.className='purple-crowd-demo';badge.textContent='紫TEST デモ値';panel.insertBefore(badge,list)}}
function demoSlots(){if(!params.has('remainingDemo'))return null;const value=count(params.get('remainingDemo'));if(value===null)return[];return[{label:params.get('crowdDemoSlot')||'紫TEST対象回',remaining:value,closed:params.get('crowdClosed')==='1'}]}
function loadCrowd(){const demo=demoSlots();render(demo||[],{demo:demo!==null})}
function patchNavigation(doc){if(!doc||doc.documentElement.dataset.purpleCrowdNav==='1')return;doc.documentElement.dataset.purpleCrowdNav='1';if(frame.contentWindow?.ASOBOON_CONFIG)frame.contentWindow.ASOBOON_CONFIG.callStatusUrl=callUrl;doc.querySelectorAll('a').forEach(a=>{if(/callstatus\.html/i.test(String(a.getAttribute('href')||''))){a.href=callUrl;a.target='_top'}});doc.addEventListener('click',e=>{const target=e.target.closest?.('[data-before-view="call"],[data-open-view="call"],#callStatusLink,#reservationCallLink');if(!target)return;e.preventDefault();top.location.href=callUrl},true)}
frame.addEventListener('load',()=>{const doc=frame.contentDocument;ensureStyle(doc);ensurePanel(doc);patchNavigation(doc);loadCrowd()});coreUrl.search=location.search;coreUrl.hash=location.hash;frame.src=coreUrl.href;
window.addEventListener('focus',loadCrowd);document.addEventListener('visibilitychange',()=>{if(!document.hidden)loadCrowd()});
window.ASOBOON_PURPLE_CROWD_TEST=Object.freeze({SETTINGS,metrics,acceptance});
})();
