import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {gzipSync} from 'node:zlib';
const read=p=>readFileSync(p,'utf8');

test('official HOME is only the Production shell with no embedded retired iframe or core boot',()=>{
 const html=read('home.html');
 assert.ok(Buffer.byteLength(html)<4000, 'the official HTML entry should be under 4 KB');
 const bridge=html.indexOf('miniapp-v2/shared/asoquest-deeplink.js');
 const shell=html.indexOf('production-shell-loader.js');
 assert.ok(bridge>0&&shell>bridge,'field NFC/QR bridge must precede Production boot');
 assert.match(html,/paramsFromLiffState\(\)/);
 assert.match(html,/window\.ASOBOON_PRODUCTION_PREVIEW=preview/);
 assert.match(html,/window\.ASOBOON_PRODUCTION_SHELL=PRODUCTION_HOME_LIVE\|\|preview/);
 assert.match(html,/<div id="app"/);
 assert.match(html,/class="asoboon-boot" role="status"/);
 assert.doesNotMatch(html,/<iframe|home-core\.html|app\/core\/|frame\.src|setInterval\(/i);
 assert.match(read('home-legacy-certified-20261007.html'),/home-core\.html/);
});

test('retired hero prototype and menu cards are never generated by the Production renderer',()=>{
 const app=read('miniapp-v2/production/app-stable-v36.js');
 const bundle=read('miniapp-v2/production/production-app.js');
 assert.match(app,/function home\(\)\{return '<section class="home-shell" aria-label="ASOBooN HOME" aria-busy="true"><\/section>'\}/);
 for(const old of ['hero-kicker','mode-toggle','fun-grid','flow-grid','actionCard(','funCard(']){
  assert.ok(!app.includes(old),'retired prototype should be absent: '+old);
  assert.ok(!bundle.includes(old),'retired prototype should be absent from bundled startup: '+old);
 }
 assert.match(app,/if\(view==='home'\)return home\(\)/);
 assert.match(read('miniapp-v2/production/home-v38.js'),/old\.outerHTML=baseHome\(\)/);
 assert.match(bundle,/function baseHome\(\)/);
});

test('Production shell preserves an existing lightweight loading state rather than reinserting it',()=>{
 const loader=read('miniapp-v2/production/production-shell-loader.js');
 assert.match(loader,/if\(!root\.querySelector\('\.asoboon-boot'\)\)/);
 assert.match(loader,/\.asoboon-boot/);
 assert.match(loader,/ASOBOON_ASOQUEST_HANDOFF/);
 assert.match(loader,/static\.line-scdn\.net\/liff\/edge\/2\/sdk\.js/);
});

test('first-paint payload uses a smaller HTML entry and respects the initial gzip budget',()=>{
 const html=read('home.html');
 const js=read('miniapp-v2/production/production-app.js');
 const css=read('miniapp-v2/production/production-app.css');
 assert.ok(Buffer.byteLength(html)<3000);
 assert.ok(gzipSync(js).length+gzipSync(css).length<40000);
});
