/** Queue Product Backend 1.0.0 — secrets live in Script Properties only. */
const QB_VERSION='1.0.0',QB_TZ='Asia/Tokyo';
const QB_PROP=Object.freeze({SHEET_ID:'QUEUE_SPREADSHEET_ID',AIRWAIT_KEY:'AIRWAIT_API_KEY',STORE_ID:'AIRWAIT_STORE_ID',STORE_NO:'AIRWAIT_STORE_NO',STAFF_KEY:'STAFF_KEY',BRAND:'BRAND_NAME',MAX_PEOPLE:'MAX_TOTAL_PEOPLE',CHILDREN_PER_ADULT:'CHILDREN_PER_ADULT',AUTO_ENABLED:'AUTO_ENABLED',AUTO_UPDATED_AT:'AUTO_UPDATED_AT',CALL_URL:'AIRWAIT_CALL_API_URL',CALL_METHOD:'AIRWAIT_CALLING_METHOD',COUNTER_ID:'AIRWAIT_COUNTER_ID'});
const QB_SHEET=Object.freeze({RES:'reservations',EVENTS:'events',MUT:'mutations'});
const QB_RES_HEADERS=['createdAt','updatedAt','operationalDay','reserveId','receiptNo','waitTypeId','waitTypeName','adults','paidChildren','infants','totalPeople','source','airwaitStatus','isCalling','calledAt','cancelledAt'];
const QB_EVENT_HEADERS=['at','type','reserveId','receiptNo','waitTypeId','message'];
const QB_MUT_HEADERS=['createdAt','updatedAt','requestId','action','scope','status','resultJson','errorCode','errorMessage'];
const QB_API=Object.freeze({waitTypes:'https://cl.airwait.jp/WCLP/api/20160600/external/stateless/wait/type/get',waitInfo:'https://airwait.jp/WCSP/api/20160600/external/stateless/store/getWaitInfo',create:'https://cl.airwait.jp/WCLP/api/20160600/external/stateless/reserve/create',reservations:'https://cl.airwait.jp/WCLP/api/external/stateless/reservations',callDefault:'https://cl.airwait.jp/WCLP/api/20160600/external/stateless/reserve/call'});
function setupProduct(){const ss=SpreadsheetApp.getActiveSpreadsheet();if(!ss)throw new Error('台帳スプレッドシートから Apps Script を開いて setupProduct() を実行してください。');const p=PropertiesService.getScriptProperties();p.setProperty(QB_PROP.SHEET_ID,ss.getId());if(!p.getProperty(QB_PROP.STAFF_KEY))p.setProperty(QB_PROP.STAFF_KEY,qbRandomKey_());if(p.getProperty(QB_PROP.AUTO_ENABLED)==null)p.setProperty(QB_PROP.AUTO_ENABLED,'0');if(!p.getProperty(QB_PROP.AUTO_UPDATED_AT))p.setProperty(QB_PROP.AUTO_UPDATED_AT,new Date().toISOString());if(!p.getProperty(QB_PROP.MAX_PEOPLE))p.setProperty(QB_PROP.MAX_PEOPLE,'10');if(!p.getProperty(QB_PROP.CHILDREN_PER_ADULT))p.setProperty(QB_PROP.CHILDREN_PER_ADULT,'3');if(!p.getProperty(QB_PROP.CALL_METHOD))p.setProperty(QB_PROP.CALL_METHOD,'KeyNORMAL');const res=qbEnsureSheet_(ss,QB_SHEET.RES,QB_RES_HEADERS);qbEnsureSheet_(ss,QB_SHEET.EVENTS,QB_EVENT_HEADERS);qbEnsureSheet_(ss,QB_SHEET.MUT,QB_MUT_HEADERS);ss.setSpreadsheetTimeZone(QB_TZ);res.getRange('D:F').setNumberFormat('@');SpreadsheetApp.flush();return checkProductSetup()}
function checkProductSetup(){const p=PropertiesService.getScriptProperties(),required=[QB_PROP.SHEET_ID,QB_PROP.AIRWAIT_KEY,QB_PROP.STORE_ID,QB_PROP.STAFF_KEY],missing=required.filter(k=>!p.getProperty(k));return{ok:missing.length===0,version:QB_VERSION,missing,brand:p.getProperty(QB_PROP.BRAND)||'',callMethod:p.getProperty(QB_PROP.CALL_METHOD)||'KeyNORMAL',callUrlConfigured:Boolean(p.getProperty(QB_PROP.CALL_URL))}}
function rotateStaffKey(){const v=qbRandomKey_();PropertiesService.getScriptProperties().setProperty(QB_PROP.STAFF_KEY,v);return v}
function doGet(e){const p=e&&e.parameter||{},a=String(p.action||'health');try{let out;if(a==='health')out={ok:true,version:QB_VERSION,service:'queue-product-backend',now:new Date().toISOString()};else if(a==='publicConfig')out=qbPublicConfig_();else if(a==='waitTypes')out=qbWaitTypes_();else if(a==='waitInfo')out=qbWaitInfo_();else if(a==='mutationStatus')out=qbMutationStatus_(p);else if(a==='staffSnapshot'){qbRequireStaff_(p.staffKey);out=qbStaffSnapshot_()}else if(a==='reservations'){qbRequireStaff_(p.staffKey);out=qbReservations_(p)}else out={ok:false,error:'unknown action'};return qbOutput_(out,p.callback)}catch(err){return qbOutput_({ok:false,version:QB_VERSION,error:String(err&&err.message||err)},p.callback)}}
function doPost(e){const p=qbParsePost_(e),a=String(p.action||''),rid=qbRequestId_(p.requestId);if(!rid)return qbJson_({ok:false,error:'invalid requestId'});const scope=['callReservation','setAutoEnabled','syncStatuses','event'].includes(a)?'staff':'public';try{if(scope==='staff')qbRequireStaff_(p.staffKey);if(qbGetMutation_(rid))return qbJson_({ok:true,duplicate:true,requestId:rid});qbSaveMutation_({requestId:rid,action:a,scope,status:'RECEIVED',result:null,errorCode:'',errorMessage:''});let result;if(a==='createReservation')result=qbCreateReservation_(p);else if(a==='callReservation')result=qbCallReservation_(p);else if(a==='setAutoEnabled')result=qbSetAuto_(p);else if(a==='syncStatuses')result=qbSyncStatusesAction_(p);else if(a==='event')result=qbEventAction_(p);else throw new Error('unknown action');qbSaveMutation_({requestId:rid,action:a,scope,status:'DONE',result,errorCode:'',errorMessage:''});return qbJson_({ok:true,requestId:rid})}catch(err){const code=qbErrorCode_(err);try{qbSaveMutation_({requestId:rid,action:a,scope,status:'ERROR',result:null,errorCode:code,errorMessage:String(err&&err.message||err).slice(0,400)})}catch(_){}return qbJson_({ok:false,requestId:rid,errorCode:code})}}
function qbPublicConfig_(){const p=PropertiesService.getScriptProperties();return{ok:true,version:QB_VERSION,brandName:p.getProperty(QB_PROP.BRAND)||'',maxTotalPeople:qbIntProp_(QB_PROP.MAX_PEOPLE,10),childrenPerAdult:qbIntProp_(QB_PROP.CHILDREN_PER_ADULT,3)}}
function qbWaitTypes_(){const d=qbAirPost_(QB_API.waitTypes,{storeId:qbProp_(QB_PROP.STORE_ID)});return{ok:true,version:QB_VERSION,waitTypeList:Array.isArray(d&&d.innerDto&&d.innerDto.waitTypeList)?d.innerDto.waitTypeList:[]}}
function qbWaitInfo_(){const d=qbAirGet_(QB_API.waitInfo,{storeId:qbProp_(QB_PROP.STORE_ID)});return{ok:true,version:QB_VERSION,innerDto:d.innerDto||{}}}
function qbReservations_(p){const body={storeId:qbProp_(QB_PROP.STORE_ID),waitTypeId:qbText_(p.waitTypeId,50),isEnabledStatus:qbText_(p.isEnabledStatus||'1',10),sortStatus:qbText_(p.sortStatus||'0',10),isDesc:qbText_(p.isDesc||'0',10),start:String(Math.max(1,Number(p.start)||1)),limit:String(Math.min(100,Math.max(1,Number(p.limit)||100)))};const d=qbAirPost_(QB_API.reservations,body);return{ok:true,version:QB_VERSION,innerDto:d.innerDto||{}}}
function qbStaffSnapshot_(){const s=qbAutoState_(),rows=qbGetReservations_('');return{ok:true,version:QB_VERSION,reservations:rows,count:rows.length,autoEnabled:s.enabled,autoUpdatedAt:s.updatedAt,callConfig:{method:qbPropOptional_(QB_PROP.CALL_METHOD)||'KeyNORMAL',counterConfigured:Boolean(qbPropOptional_(QB_PROP.COUNTER_ID)),customUrl:Boolean(qbPropOptional_(QB_PROP.CALL_URL))}}}
function qbCreateReservation_(p){const adults=qbInt_(p.adults,1,100),paid=qbInt_(p.paidChildren,0,100),infants=qbInt_(p.infants,0,100),children=paid+infants,total=adults+children,max=qbIntProp_(QB_PROP.MAX_PEOPLE,10),ratio=qbIntProp_(QB_PROP.CHILDREN_PER_ADULT,3);if(total>max)throw new Error('人数上限を超えています。');if(children>adults*ratio)throw new Error('おとな1名あたりの子ども人数上限を超えています。');const waitTypeId=qbText_(p.waitTypeId,50);if(!waitTypeId)throw new Error('waitTypeId required');const day=qbNormalizeDay_(p.operationalDay);if(!day)throw new Error('operationalDay required');const d=qbAirPost_(QB_API.create,{storeId:qbProp_(QB_PROP.STORE_ID),numPerson:String(adults),numPersonChild:String(children),waitTypeId,langType:'KeyJPN',autoPrintFlg:'false'}),dto=d.innerDto||{},reserveId=qbReserveId_(dto.reserveId),receiptNo=qbText_(dto.receiptNo,50);if(!reserveId||!receiptNo)throw new Error('AirWAITから受付番号を取得できませんでした。');const rec={reserveId,receiptNo,waitTypeId,waitTypeName:qbText_(p.waitTypeName,120),operationalDay:day,adults,paidChildren:paid,infants,totalPeople:total,source:qbText_(p.source||'queue-product',100)};qbUpsertReservation_(rec);qbAppendEvent_({type:'RESERVATION_CREATED',reserveId,receiptNo,waitTypeId,message:`${total} people`});return{reserveId,receiptNo,shortUrl:dto.shortUrl||null,operationalDay:day,totalPeople:total}}
function qbCallReservation_(p){const reserveId=qbReserveId_(p.reserveId);if(!reserveId)throw new Error('invalid reserveId');const props=PropertiesService.getScriptProperties(),method=props.getProperty(QB_PROP.CALL_METHOD)||'KeyNORMAL',url=props.getProperty(QB_PROP.CALL_URL)||QB_API.callDefault,body={storeId:qbProp_(QB_PROP.STORE_ID),reserveId,callingMethodType:method},counter=props.getProperty(QB_PROP.COUNTER_ID)||'';if(counter)body.counterId=counter;const d=qbAirPost_(url,body);qbUpdateReservation_(reserveId,{isCalling:'1',calledAt:new Date().toISOString()});qbAppendEvent_({type:'CALLED',reserveId,receiptNo:'',waitTypeId:'',message:`method=${method}`});return{ok:true,reserveId,resultCode:String(d.resultCode&&d.resultCode.code||'0000')}}
function qbSetAuto_(p){const enabled=String(p.enabled)==='1'||String(p.enabled).toLowerCase()==='true',props=PropertiesService.getScriptProperties(),now=new Date().toISOString();props.setProperty(QB_PROP.AUTO_ENABLED,enabled?'1':'0');props.setProperty(QB_PROP.AUTO_UPDATED_AT,now);qbAppendEvent_({type:enabled?'AUTO_ON':'AUTO_OFF',reserveId:'',receiptNo:'',waitTypeId:'',message:'persistent auto'});return{enabled,updatedAt:now}}
function qbSyncStatusesAction_(p){let items;try{items=JSON.parse(String(p.items||'[]'))}catch(_){throw new Error('invalid items JSON')}if(!Array.isArray(items))throw new Error('items must be array');items.slice(0,3000).forEach(item=>{const id=qbReserveId_(item.reserveId);if(!id)return;const status=qbText_(item.status,20),isCalling=String(item.isCalling)==='1'?'1':'0',patch={airwaitStatus:status,isCalling};if(status==='3')patch.cancelledAt=new Date().toISOString();qbUpdateReservation_(id,patch)});return{count:Math.min(items.length,3000)}}
function qbEventAction_(p){qbAppendEvent_({type:qbText_(p.type||'EVENT',50),reserveId:qbReserveId_(p.reserveId),receiptNo:qbText_(p.receiptNo,50),waitTypeId:qbText_(p.waitTypeId,50),message:qbText_(p.message,500)});return{ok:true}}
function qbMutationStatus_(p){const rid=qbRequestId_(p.requestId);if(!rid)return{ok:false,error:'invalid requestId'};const row=qbGetMutation_(rid);if(!row)return{ok:true,found:false};if(row.scope==='staff')qbRequireStaff_(p.staffKey);let result={};try{result=row.resultJson?JSON.parse(row.resultJson):{}}catch(_){}return{ok:true,found:true,status:row.status,action:row.action,result,errorCode:row.errorCode||'',errorMessage:row.errorMessage||''}}
function qbAirPost_(u,b){return qbAirRequest_(u,'post',b)}function qbAirGet_(u,p){return qbAirRequest_(u,'get',p)}
function qbAirRequest_(base,method,params){const key=qbProp_(QB_PROP.AIRWAIT_KEY),u=base+(base.indexOf('?')>=0?'&':'?')+'key='+encodeURIComponent(key),opts={method,followRedirects:true,muteHttpExceptions:true,headers:{Accept:'application/json'}};let finalUrl=u;if(method==='post'){opts.contentType='application/x-www-form-urlencoded; charset=UTF-8';opts.payload=params||{}}else{const q=Object.keys(params||{}).map(k=>encodeURIComponent(k)+'='+encodeURIComponent(String(params[k]))).join('&');if(q)finalUrl+='&'+q}const r=UrlFetchApp.fetch(finalUrl,opts),status=r.getResponseCode(),text=r.getContentText();let d;try{d=JSON.parse(text)}catch(_){throw new Error('AirWAIT response parse error / HTTP '+status)}const code=String(d&&d.resultCode&&d.resultCode.code||'');if(status<200||status>=300)throw new Error('AirWAIT HTTP '+status);if(!(d&&d.success===true)&&code!=='0000'){const msg=String(d&&d.resultCode&&d.resultCode.defaultMessage||'AirWAIT API error'),vr=Array.isArray(d&&d.validationResults)?d.validationResults.map(x=>`${x.field||''}:${x.msg||''}`).join(' / '):'';throw new Error(`AirWAIT ${code||'?'}: ${msg}${vr?' / '+vr:''}`)}return d}
function qbUpsertReservation_(rec){const lock=LockService.getScriptLock();lock.waitLock(30000);try{const sh=qbSheet_(QB_SHEET.RES,QB_RES_HEADERS),row=qbFindReservationRow_(rec.reserveId),now=new Date().toISOString();let created=now,status='0',calling='0',called='',cancelled='';if(row>0){const old=sh.getRange(row,1,1,QB_RES_HEADERS.length).getDisplayValues()[0];created=old[0]||now;status=old[12]||'0';calling=old[13]||'0';called=old[14]||'';cancelled=old[15]||''}const values=[[created,now,rec.operationalDay,String(rec.reserveId),String(rec.receiptNo),String(rec.waitTypeId),rec.waitTypeName,rec.adults,rec.paidChildren,rec.infants,rec.totalPeople,rec.source,status,calling,called,cancelled]],target=row>0?row:Math.max(2,sh.getLastRow()+1);qbEnsureRows_(sh,target);sh.getRange(target,4,1,3).setNumberFormat('@');sh.getRange(target,1,1,QB_RES_HEADERS.length).setValues(values);SpreadsheetApp.flush();return{row:target,isNew:row<1}}finally{lock.releaseLock()}}
function qbUpdateReservation_(id,patch){const sh=qbSheet_(QB_SHEET.RES,QB_RES_HEADERS),row=qbFindReservationRow_(id);if(row<1)return false;const values=sh.getRange(row,1,1,QB_RES_HEADERS.length).getValues()[0];Object.keys(patch||{}).forEach(k=>{const i=QB_RES_HEADERS.indexOf(k);if(i>=0)values[i]=patch[k]});values[1]=new Date().toISOString();sh.getRange(row,1,1,QB_RES_HEADERS.length).setValues([values]);return true}
function qbGetReservations_(day){const sh=qbSheet_(QB_SHEET.RES,QB_RES_HEADERS),last=sh.getLastRow();if(last<=1)return[];return sh.getRange(2,1,last-1,QB_RES_HEADERS.length).getValues().map(r=>qbRowObj_(r,QB_RES_HEADERS)).map(x=>({...x,operationalDay:qbNormalizeDay_(x.operationalDay),reserveId:qbReserveId_(x.reserveId)})).filter(x=>!day||x.operationalDay===day).sort((a,b)=>Date.parse(a.createdAt)-Date.parse(b.createdAt))}
function qbFindReservationRow_(id){const sh=qbSheet_(QB_SHEET.RES,QB_RES_HEADERS),last=sh.getLastRow();if(last<=1)return-1,target=qbReserveId_(id),values=sh.getRange(2,4,last-1,1).getDisplayValues();for(let i=0;i<values.length;i++)if(qbReserveId_(values[i][0])===target)return i+2;return-1}
function qbSaveMutation_(m){const lock=LockService.getScriptLock();lock.waitLock(30000);try{const sh=qbSheet_(QB_SHEET.MUT,QB_MUT_HEADERS),row=qbFindMutationRow_(m.requestId),now=new Date().toISOString(),created=row>0?String(sh.getRange(row,1).getDisplayValue()||now):now,values=[[created,now,m.requestId,m.action,m.scope,m.status,m.result?JSON.stringify(m.result):'',m.errorCode||'',m.errorMessage||'']],target=row>0?row:Math.max(2,sh.getLastRow()+1);qbEnsureRows_(sh,target);sh.getRange(target,1,1,QB_MUT_HEADERS.length).setValues(values);SpreadsheetApp.flush()}finally{lock.releaseLock()}}
function qbGetMutation_(rid){const sh=qbSheet_(QB_SHEET.MUT,QB_MUT_HEADERS),row=qbFindMutationRow_(rid);return row>0?qbRowObj_(sh.getRange(row,1,1,QB_MUT_HEADERS.length).getValues()[0],QB_MUT_HEADERS):null}
function qbFindMutationRow_(rid){const sh=qbSheet_(QB_SHEET.MUT,QB_MUT_HEADERS),last=sh.getLastRow();if(last<=1)return-1;const vals=sh.getRange(2,3,last-1,1).getDisplayValues();for(let i=0;i<vals.length;i++)if(String(vals[i][0])===String(rid))return i+2;return-1}
function qbAppendEvent_(e){const sh=qbSheet_(QB_SHEET.EVENTS,QB_EVENT_HEADERS),row=Math.max(2,sh.getLastRow()+1);qbEnsureRows_(sh,row);sh.getRange(row,1,1,QB_EVENT_HEADERS.length).setValues([[new Date().toISOString(),qbText_(e.type,50),qbReserveId_(e.reserveId),qbText_(e.receiptNo,50),qbText_(e.waitTypeId,50),qbText_(e.message,500)]])}
function qbAutoState_(){const p=PropertiesService.getScriptProperties();return{enabled:p.getProperty(QB_PROP.AUTO_ENABLED)==='1',updatedAt:p.getProperty(QB_PROP.AUTO_UPDATED_AT)||''}}
function qbSheet_(n,h){return qbEnsureSheet_(SpreadsheetApp.openById(qbProp_(QB_PROP.SHEET_ID)),n,h)}function qbEnsureSheet_(ss,n,h){let sh=ss.getSheetByName(n);if(!sh)sh=ss.insertSheet(n);if(sh.getMaxColumns()<h.length)sh.insertColumnsAfter(sh.getMaxColumns(),h.length-sh.getMaxColumns());const cur=sh.getRange(1,1,1,h.length).getDisplayValues()[0];if(cur.join('|')!==h.join('|'))sh.getRange(1,1,1,h.length).setValues([h]);sh.setFrozenRows(1);return sh}function qbEnsureRows_(sh,row){if(sh.getMaxRows()<row)sh.insertRowsAfter(sh.getMaxRows(),row-sh.getMaxRows())}
function qbRowObj_(row,h){const o={};h.forEach((k,i)=>{const v=row[i];o[k]=v instanceof Date?Utilities.formatDate(v,QB_TZ,"yyyy-MM-dd'T'HH:mm:ssXXX"):String(v==null?'':v)});return o}function qbParsePost_(e){const p={};Object.keys(e&&e.parameter||{}).forEach(k=>p[k]=e.parameter[k]);return p}
function qbOutput_(o,cb){const t=JSON.stringify(o);if(cb&&/^[A-Za-z_$][\w$\.]{0,100}$/.test(cb))return ContentService.createTextOutput(`${cb}(${t});`).setMimeType(ContentService.MimeType.JAVASCRIPT);return ContentService.createTextOutput(t).setMimeType(ContentService.MimeType.JSON)}function qbJson_(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON)}
function qbRequireStaff_(v){if(!v||String(v)!==qbProp_(QB_PROP.STAFF_KEY))throw new Error('staff auth failed')}function qbProp_(k){const v=PropertiesService.getScriptProperties().getProperty(k);if(!v)throw new Error('Script Property missing: '+k);return v}function qbPropOptional_(k){return PropertiesService.getScriptProperties().getProperty(k)||''}function qbIntProp_(k,f){const n=Number(qbPropOptional_(k));return Number.isFinite(n)&&n>0?Math.floor(n):f}function qbInt_(v,min,max){const n=Math.floor(Number(v));if(!Number.isFinite(n)||n<min||n>max)throw new Error('invalid number');return n}function qbText_(v,max){return String(v==null?'':v).trim().slice(0,max||200)}
function qbReserveId_(v){const s=String(v==null?'':v).normalize('NFKC').trim();if(/^\d{1,12}$/.test(s))return s.padStart(12,'0');return /^[A-Za-z0-9_-]{1,100}$/.test(s)?s:''}function qbRequestId_(v){const s=String(v||'').trim();return /^[A-Za-z0-9_-]{20,100}$/.test(s)?s:''}function qbNormalizeDay_(v){if(v instanceof Date&&!isNaN(v.getTime()))return Utilities.formatDate(v,QB_TZ,'yyyy-MM-dd');const s=String(v==null?'':v).trim();let m=s.match(/^(\d{4})[-\/]([01]?\d)[-\/]([0-3]?\d)$/);if(m)return `${m[1]}-${String(Number(m[2])).padStart(2,'0')}-${String(Number(m[3])).padStart(2,'0')}`;const d=new Date(s);return isNaN(d.getTime())?'':Utilities.formatDate(d,QB_TZ,'yyyy-MM-dd')}function qbErrorCode_(e){const s=String(e&&e.message||e||'');if(/AirWAIT/.test(s))return'AIRWAIT_ERROR';if(/staff auth/.test(s))return'AUTH_ERROR';if(/required|invalid|上限/.test(s))return'VALIDATION_ERROR';return'BACKEND_ERROR'}function qbRandomKey_(){const b=[];for(let i=0;i<6;i++)b.push(Utilities.getUuid().replace(/-/g,''));return b.join('').slice(0,64)}
