/* ASOBooN LINE MINI App v2 / new HOME + same-app router */
(()=>{'use strict';
const C=window.ASOBOON_V2_COMMON||{};
const E=window.ASOBOON_V2_ENV||{};
const F=E.featureFlags||{};
const root=document.getElementById('app');
const state={mode:'before',view:'home',liffReady:false,inClient:false,displayName:'',bootError:''};
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const q=()=>new URLSearchParams(location.search);
function normalizeView(v){return Object.values(C.routes||{}).includes(String(v||''))?String(v):'home'}
function normalizeMode(v){return String(v)==='inside'?'inside':'before'}
function routeUrl(view,extra={}){const u=new URL(E.endpoint||location.href,location.href);u.searchParams.set('view',normalizeView(view));u.searchParams.set('mode',state.mode);Object.entries(extra).forEach(([k,v])=>{if(v!==''&&v!=null)u.searchParams.set(k,String(v))});return u.href}
function go(view,{replace=false,...extra}={}){const u=routeUrl(view,extra);if(replace)history.replaceState({},'',u);else history.pushState({},'',u);readRoute();render();window.scrollTo({top:0,behavior:'smooth'})}
function setMode(mode){state.mode=normalizeMode(mode);const u=new URL(location.href);u.searchParams.set('mode',state.mode);u.searchParams.set('view',state.view);history.replaceState({},'',u);render()}
function readRoute(){const p=q();state.view=normalizeView(p.get('view'));state.mode=normalizeMode(p.get('mode'))}
function feature(route){const map={reception:'reception',callstatus:'callstatus',timeguide:'timeguide',first:'firstGuide',entry:'entryGuide',rules:'rules',stamp:'stamp',omikuji:'omikuji',game:'game',parking:'parking'};const k=map[route];return k?F[k]===true:true}
function actionCard(view,kind,title,desc,cls=''){const enabled=feature(view);return `<button class="flow-card ${cls}" data-view="${view}" type="button"><span class="mini">${esc(kind)}</span><strong>${esc(title)}</strong><p>${esc(desc)}</p><span class="arrow">›</span>${enabled?'':'<span class="soon">準備中</span>'}</button>`}
function funCard(view,emoji,title,sub){const enabled=feature(view);return `<button class="fun-card" data-view="${view}" type="button"><span class="emoji">${emoji}</span><strong>${esc(title)}</strong><small>${esc(sub)}</small>${enabled?'':'<span class="soon">統合中</span>'}</button>`}
function home(){const inside=state.mode==='inside';return `<section class="home-shell"><div class="hero ${inside?'inside':''}"><span class="hero-kicker">ASOBooN OFFICIAL MINI APP · ${esc(E.environmentLabel||'')}</span><h1>${inside?'館内ナビ':'来場前ナビ'}<span>家族の冒険を、ひとつのLINEミニアプリで。</span></h1><p>${inside?'入場後によく使う機能をまとめています。':'受付から呼出まで、ここから迷わず進めます。'}</p></div><div class="mode-toggle" aria-label="表示切替"><button type="button" data-mode="before" class="${inside?'':'active'}">🚗 来場前</button><button type="button" data-mode="inside" class="${inside?'active':''}">🎪 館内</button></div><div class="section-title">あそぶ <small>いつでも上段固定</small></div><div class="fun-grid">${funCard('game','🏎️','ミニゲーム','ブーンシリーズ')}${funCard('omikuji','🎯','おみくじ','今日の運勢')}${funCard('stamp','🔩','スタンプ','館内ラリー')}</div><div class="section-title">${inside?'館内で使う':'入場までの流れ'}</div><div class="flow-grid">${inside?`${actionCard('timeguide','PLAY TIME','何時まであそべる？','入場時刻から利用終了の目安を確認','primary')}${actionCard('rules','RULES','館内ルール','遊ぶ前に大切なルールを確認')}${actionCard('entry','ENTRY / EXIT','入退場方法','受付・退場の流れを確認')}${actionCard('callstatus','CALL STATUS','呼出状況','受付番号の現在地を確認','call')}`:`${actionCard('reception','TODAY RECEPTION','当日受付','WEB受付・現地受付をここから','primary')}${actionCard('entry','BEFORE ENTRY','入場まで','受付後から入場までの流れ')}${actionCard('first','FIRST VISIT','初めての方','料金・対象年齢・利用方法')}${actionCard('callstatus','CALL STATUS','呼出状況','順番・呼出状態を確認','call')}${actionCard('parking','ACCESS','駐車場・アクセス','川口ハイウェイオアシスへの行き方')}${actionCard('rules','RULES','館内ルール','ご利用前に確認')}`}</div><div class="notice"><strong>新HOME：</strong> 認証対象ASOBooN MINI App内で主要機能を完結させるための次期構成です。別LIFFへの遷移は行いません。</div></section>`}
function disabledPage(view,title,icon){return `<section class="page-card"><div class="page-head"><small>ASOBooN / ${esc(E.environmentLabel||'')}</small><h2>${esc(title)}</h2></div><div class="disabled-card"><div class="disabled-icon">${icon}</div><h3>新本番版へ統合中</h3><p>この機能は、旧LIFFやAirウェイト公式画面へ逃がさず、同じASOBooN MINI Appの中で完結する形に作り替えています。</p><span class="pill">${esc(view)} · SAFE HOLD</span></div></section>`}
function firstPage(){return `<section class="page-card"><div class="page-head orange"><small>FIRST VISIT</small><h2>初めての方へ</h2></div><div class="page-body"><h3>ASOBooNは0歳から小学校6年生まで</h3><p>川口ハイウェイオアシス内の屋内あそび場です。保護者1名につき、お子さま3名までご利用いただけます。</p><div class="step-list"><div class="step"><b>1</b><span>LINEミニアプリから当日受付</span></div><div class="step"><b>2</b><span>呼出状況を確認しながら待機</span></div><div class="step"><b>3</b><span>呼出後30分以内を目安に受付へ</span></div><div class="step"><b>4</b><span>受付・会計後に入場</span></div></div><div class="timebox"><small>通常料金</small><strong>大人 600円 / 子ども 900円</strong><p>6か月未満は、2人目以降の追加料金はかかりません。</p></div></div></section>`}
function entryPage(){return `<section class="page-card"><div class="page-head green"><small>ENTRY / EXIT</small><h2>入退場方法</h2></div><div class="page-body"><h3>受付番号を準備して受付へ</h3><p>呼出状態になったら、受付番号を確認できる状態で受付へお越しください。</p><div class="step-list"><div class="step"><b>1</b><span>当日受付を完了する</span></div><div class="step"><b>2</b><span>LINE通知・呼出状況を確認する</span></div><div class="step"><b>3</b><span>呼出されたら受付・会計へ</span></div><div class="step"><b>4</b><span>入場後は利用時間案内を確認</span></div></div></div></section>`}
function rulesPage(){return `<section class="page-card"><div class="page-head"><small>SAFETY & PLAY</small><h2>館内ルール</h2></div><div class="page-body"><p>安全を守りながら、子ども自身が考えて挑戦できる遊びを大切にしています。</p><div class="rule-list"><div class="rule"><strong>保護者の方と一緒に</strong>お子さまから目を離さず、一緒に館内をお楽しみください。</div><div class="rule"><strong>危険な行為は止める</strong>他のお客さまにぶつかる行為や、設備の想定外利用はスタッフがお声がけします。</div><div class="rule"><strong>困った時はスタッフへ</strong>けが・迷子・体調不良などは近くのスタッフへお知らせください。</div></div></div></section>`}
function timePage(){return `<section class="page-card"><div class="page-head green"><small>PLAY TIME</small><h2>何時まであそべる？</h2></div><div class="page-body"><h3>利用時間は営業区分で変わります</h3><p>新版では営業カレンダーを正本にし、曜日から推測しません。入場時刻を登録すると、その日の利用時間・閉館時刻を使って終了目安を表示します。</p><div class="timebox"><small>新HOME段階</small><strong>営業日エンジン接続待ち</strong><p>誤案内防止のため、接続完了までは時刻を推測表示しません。</p></div></div></section>`}
function parkingPage(){return `<section class="page-card"><div class="page-head orange"><small>ACCESS</small><h2>駐車場・アクセス</h2></div><div class="page-body"><h3>川口ハイウェイオアシス内</h3><p>ASOBooNは川口ハイウェイオアシス内にあります。新MINI Appでは、外部サイトを開く案内と主要機能を明確に分離します。</p><div class="rule-list"><div class="rule"><strong>主要機能ではありません</strong>地図・施設公式サイト等の外部リンクは、必要な場合だけ明示して開く設計にします。</div></div></div></section>`}
function pageFor(view){if(view==='home')return home();if(!feature(view)){const meta={reception:['当日受付','🎫'],callstatus:['呼出状況','🔔'],stamp:['スタンプラリー','🔩'],omikuji:['おみくじ','🎯'],game:['ミニゲーム','🏎️']}[view]||[view,'🛠️'];return disabledPage(view,meta[0],meta[1])}if(view==='first')return firstPage();if(view==='entry')return entryPage();if(view==='rules')return rulesPage();if(view==='timeguide')return timePage();if(view==='parking')return parkingPage();return disabledPage(view,view,'🛠️')}
function shell(){const homeView=state.view==='home';const lineText=state.liffReady?(state.inClient?'LINE内':'ブラウザプレビュー'):(state.bootError?'LIFF確認エラー':'LIFF確認中');const dot=state.liffReady?(state.inClient?'ok':'warn'):(state.bootError?'warn':'');return `<div class="devbar"><span><i class="dot ${dot}"></i><b>${esc(E.environmentLabel||'ENV')}</b> · ${esc(lineText)}</span><span>v${esc(C.version||'')}</span></div><header class="topbar"><button class="iconbtn ${homeView?'ghost':''}" id="backBtn" type="button" aria-label="戻る">‹</button><div class="brand"><strong>ASOBooN</strong><small>OFFICIAL LINE MINI APP · NEW HOME</small></div><button class="iconbtn ${homeView?'ghost':''}" data-view="home" type="button" aria-label="ホーム">⌂</button></header><main class="view active">${pageFor(state.view)}</main><footer class="footer"><b>ASOBooN MINI APP v2</b><br>${esc(E.environmentLabel||'')} / same-app routing / no legacy LIFF</footer>`}
function bind(){root.querySelectorAll('[data-view]').forEach(el=>el.addEventListener('click',()=>go(el.dataset.view)));root.querySelectorAll('[data-mode]').forEach(el=>el.addEventListener('click',()=>setMode(el.dataset.mode)));const back=document.getElementById('backBtn');if(back&&!back.classList.contains('ghost'))back.addEventListener('click',()=>{if(history.length>1)history.back();else go('home',{replace:true})})}
function render(){document.title=`${state.view==='home'?'ASOBooN 新HOME':'ASOBooN'}｜LINEミニアプリ`;root.innerHTML=shell();bind()}
async function initLiff(){if(!E.liffId||!window.liff){state.bootError='LIFF_SDK_NOT_READY';render();return}try{await liff.init({liffId:E.liffId});state.liffReady=true;state.inClient=Boolean(liff.isInClient());if(liff.isLoggedIn()){try{const p=await liff.getProfile();state.displayName=String(p?.displayName||'')}catch{}}}catch(e){state.bootError=String(e?.message||e||'LIFF_INIT_FAILED').slice(0,120)}render()}
window.addEventListener('popstate',()=>{readRoute();render()});readRoute();render();void initLiff();
})();
