/* ASOBooN LINE MINI App v2 / same-app reception flow */
(()=>{'use strict';
const E=window.ASOBOON_V2_ENV||{},R=window.ASOBOON_V2_RULES||{},D=window.ASOBOON_V2_BUSINESS_DAY||{};
const CACHE_KEY='asoboon_v2_current_reservation_develop_v1';
const CALL_KEY='asoboon_v2_callstatus_develop_v1';
const S={mode:'web',day:null,slots:[],slot:null,adult:1,child:0,infant:0,agree:false,location:null,health:null,canCreate:false,busy:false,locked:false,generation:0};
let CTX=null;
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const total=()=>S.adult+S.child+S.infant;
const kids=()=>S.child+S.infant;
const price=()=>typeof R.priceFor==='function'?R.priceFor(S):S.adult*600+S.child*900+(S.infant>0?900:0);
const validPeople=()=>S.adult>=1&&S.child>=0&&S.infant>=0&&total()<=Number(R.limits?.maxTotalPeople||10)&&kids()<=S.adult*Number(R.limits?.childrenPerAdult||3);
const fmtYen=n=>Number(n||0).toLocaleString('ja-JP')+'円';
const fmtDate=v=>{const m=String(v||'').match(/^\d{4}-(\d{2})-(\d{2})$/);return m?`${+m[1]}月${+m[2]}日`:String(v||'')};
function render(){return `<section class="page-card"><div class="page-head orange"><small>TODAY RECEPTION / NEW HOME</small><h2>当日受付</h2></div><div class="page-body"><div class="rec-wrap"><div id="recStatus" class="rec-status">LINE接続と営業カレンダーを確認しています…</div><div class="rec-methods"><button id="recWeb" class="rec-method active" type="button"><span>🌐</span><strong>WEB受付</strong><small>来場前にLINEミニアプリの中で受付します。</small></button><button id="recOnsite" class="rec-method onsite" type="button"><span>📍</span><strong>現地受付</strong><small>ASOBooN付近で現在地を確認して受付します。</small></button></div><div id="recDay" class="rec-day"><span><small>営業区分</small><strong>確認中</strong></span><b>—</b></div><h3 class="rec-title">① ご利用の回</h3><div id="recSlots" class="rec-slots"><div class="rec-status">営業区分を確認しています…</div></div><div id="recLocation" class="rec-location" hidden><p id="recLocationText">現地受付は、施設から500m以内・位置情報の精度200m以内を確認します。</p><button id="recLocationBtn" type="button">現在地を確認する</button></div><h3 class="rec-title">② ご利用人数</h3><div class="rec-people"><div class="rec-person"><span><strong>おとな</strong><small>600円</small></span><div class="rec-stepper"><button type="button" data-rec-k="adult" data-rec-d="-1">−</button><output id="recAdult">1</output><button type="button" data-rec-k="adult" data-rec-d="1">＋</button></div></div><div class="rec-person"><span><strong>こども</strong><small>6か月〜小6 / 900円</small></span><div class="rec-stepper"><button type="button" data-rec-k="child" data-rec-d="-1">−</button><output id="recChild">0</output><button type="button" data-rec-k="child" data-rec-d="1">＋</button></div></div><div class="rec-person"><span><strong>0〜5か月</strong><small>1人目900円 / 2人目以降無料</small></span><div class="rec-stepper"><button type="button" data-rec-k="infant" data-rec-d="-1">−</button><output id="recInfant">0</output><button type="button" data-rec-k="infant" data-rec-d="1">＋</button></div></div></div><div class="rec-summary"><div class="rec-line"><span>受付方法</span><strong id="recModeLabel">WEB受付</strong></div><div class="rec-line"><span>回</span><strong id="recSlotLabel">未選択</strong></div><div class="rec-line"><span>合計人数</span><strong id="recPeopleTotal">1名</strong></div><div class="rec-line total"><span>料金目安</span><strong id="recPrice">600円</strong></div></div><div id="recPeopleMsg" class="rec-status ok">この人数で受付できます。</div><label class="rec-agree"><input id="recAgree" type="checkbox"><span>受付内容を確認しました。受付確定後は、結果が不明な場合に同じ受付を繰り返し送信しないことを確認します。</span></label><button id="recSubmit" class="rec-submit" type="button" disabled>受付確定（接続準備中）</button><div id="recSafe" class="rec-safe">🔒 AirWAIT APIキーやLINEの秘密情報はブラウザに置きません。正式な受付作成はサーバー側Gatewayだけが実行します。</div><div id="recResult" hidden></div></div></div></section>`}
function status(text,kind=''){const el=$('recStatus');if(!el)return;el.className='rec-status'+(kind?' '+kind:'');el.textContent=text}
function backendReady(){try{return Boolean(E.backendUrl&&/^https:\/\//.test(String(E.backendUrl)))}catch{return false}}
function jsonp(action,params={},timeout=10000){return new Promise((resolve,reject)=>{if(!backendReady())return reject(Error('NEW_GATEWAY_NOT_CONFIGURED'));const cb=`__asoV2_${Date.now()}_${Math.random().toString(36).slice(2)}`,u=new URL(E.backendUrl),s=document.createElement('script');let done=false;const timer=setTimeout(()=>finish(Error('Gateway timeout')),timeout);function finish(e,v){if(done)return;done=true;clearTimeout(timer);try{delete window[cb]}catch{}s.remove();e?reject(e):resolve(v)}window[cb]=v=>finish(null,v);u.searchParams.set('action',action);u.searchParams.set('callback',cb);Object.entries(params).forEach(([k,v])=>u.searchParams.set(k,String(v??'')));u.searchParams.set('_',Date.now());s.src=u;s.onerror=()=>finish(Error('Gateway read failed'));document.head.appendChild(s)})}
function requestId(){try{return'v2_'+crypto.randomUUID()}catch{return'v2_'+Date.now()+'_'+Math.random().toString(36).slice(2)}}
async function post(action,body){const id=requestId(),payload={action,requestId:id,...body};try{await fetch(E.backendUrl,{method:'POST',mode:'no-cors',credentials:'omit',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body:new URLSearchParams(Object.entries(payload).map(([k,v])=>[k,String(v??'')])),cache:'no-store',keepalive:true})}catch{}for(const ms of[400,800,1200,1800,2600,3600,5000]){await sleep(ms);try{const r=await jsonp('requestStatus',{requestId:id});if(r&&r.found)return r}catch{}}const e=Error('受付結果を確認できません。');e.ambiguous=true;throw e}
function healthSupportsOfficialDevelop(h){if(!(h&&h.ok===true&&h.createRequiresVerifiedLiff===true))return false;if(h.officialDevelopEnabled===true)return true;if(Array.isArray(h.acceptedClientIds)&&h.acceptedClientIds.map(String).includes(String(E.channelId||'')))return true;return false}
function lineState(){return typeof CTX?.lineState==='function'?CTX.lineState():{liffReady:false,inClient:false,booting:true}}
async function waitForLine(){let st=lineState();if(st.booting||!st.liffReady){await Promise.race([new Promise(resolve=>window.addEventListener('asoboon:v2-liff-ready',resolve,{once:true})),sleep(6000)]);st=lineState()}if(!st.liffReady)throw Error('LINE接続を確認できません。いったん閉じて開き直してください。');if(!st.inClient)throw Error('LINEミニアプリ内から開いてください。');if(!window.liff||!liff.isLoggedIn())throw Error('LINEログインを確認できません。');return true}
function allowedUsage(actual,mode){const usage=String(actual?.usageDispType||'');if(!usage)return true;return mode==='web'?usage==='01'||usage==='03':usage==='01'||usage==='02'}
function buildSlots(waitTypes){const configured=typeof R.slotsFor==='function'?R.slotsFor(S.day?.businessType):[];return configured.map(rule=>{const actual=Array.isArray(waitTypes)?waitTypes.find(x=>String(x.waitTypeId||'')===String(rule.waitTypeId)):null;if(actual&&(actual.dispFlg===false||!allowedUsage(actual,S.mode)))return null;return{...rule,actual}}).filter(Boolean)}
function renderSlots(){const el=$('recSlots');if(!el)return;if(S.day?.isClosed){el.innerHTML='<div class="rec-status bad">本日は休館日です。</div>';return}if(!S.slots.length){el.innerHTML='<div class="rec-status warn">現在選択できる受付枠がありません。</div>';return}el.innerHTML=S.slots.map(s=>`<button type="button" class="rec-slot ${S.slot?.waitTypeId===s.waitTypeId?'active':''}" data-rec-slot="${esc(s.waitTypeId)}"><strong>${esc(s.label)}</strong><small>${esc(s.actual?.waitTypeName||s.detail||'')}</small></button>`).join('')}
function locationOk(){return S.mode!=='onsite'||Boolean(S.location?.ok)}
function renderForm(){if(!$('recAdult'))return;$('recAdult').textContent=S.adult;$('recChild').textContent=S.child;$('recInfant').textContent=S.infant;$('recModeLabel').textContent=S.mode==='web'?'WEB受付':'現地受付';$('recSlotLabel').textContent=S.slot?.label||'未選択';$('recPeopleTotal').textContent=total()+'名';$('recPrice').textContent=fmtYen(price());$('recWeb').classList.toggle('active',S.mode==='web');$('recOnsite').classList.toggle('active',S.mode==='onsite');$('recLocation').hidden=S.mode!=='onsite';const peopleOK=validPeople(),msg=$('recPeopleMsg');msg.className='rec-status '+(peopleOK?'ok':'bad');msg.textContent=peopleOK?'この人数で受付できます。':`保護者1名につきお子さま3名まで、1組合計${Number(R.limits?.maxTotalPeople||10)}名までです。`;document.querySelectorAll('[data-rec-k]').forEach(b=>{const k=b.dataset.recK,d=+b.dataset.recD;if(d<0){b.disabled=k==='adult'?S.adult<=1||kids()>(S.adult-1)*Number(R.limits?.childrenPerAdult||3):S[k]<=0}else b.disabled=total()>=Number(R.limits?.maxTotalPeople||10)||(k!=='adult'&&kids()>=S.adult*Number(R.limits?.childrenPerAdult||3))});const submit=$('recSubmit'),ready=peopleOK&&S.slot&&S.agree&&locationOk()&&!S.day?.isClosed&&!S.busy&&!S.locked&&S.canCreate;submit.disabled=!ready;submit.textContent=S.busy?'受付中…':S.canCreate?'受付を確定する':'受付確定（Gateway接続待ち）'}
function distanceM(a,b,c,d){const Rm=6371000,rad=x=>x*Math.PI/180,x=rad(c-a),y=rad(d-b),q=Math.sin(x/2)**2+Math.cos(rad(a))*Math.cos(rad(c))*Math.sin(y/2)**2;return 2*Rm*Math.atan2(Math.sqrt(q),Math.sqrt(1-q))}
async function checkLocation(){const txt=$('recLocationText'),btn=$('recLocationBtn');if(!navigator.geolocation){txt.textContent='この端末では位置情報を利用できません。';return}btn.disabled=true;txt.textContent='現在地を確認しています…';try{const p=await new Promise((resolve,reject)=>navigator.geolocation.getCurrentPosition(resolve,reject,{enableHighAccuracy:true,timeout:10000,maximumAge:0}));const g=R.geofence||{},lat=+p.coords.latitude,lng=+p.coords.longitude,accuracy=+p.coords.accuracy,age=Math.max(0,Date.now()-Number(p.timestamp||Date.now())),distance=distanceM(+g.lat,+g.lng,lat,lng),ok=distance<=Number(g.radiusM||500)&&accuracy<=Number(g.maxAccuracyM||200)&&age<=Number(g.maxAgeMs||120000);S.location={ok,lat,lng,accuracy,timestamp:Number(p.timestamp||Date.now()),distance};txt.textContent=ok?`現在地OK：施設から約${Math.round(distance)}m / 精度 約${Math.round(accuracy)}m`:`現地受付の範囲外です：距離 約${Math.round(distance)}m / 精度 約${Math.round(accuracy)}m`;txt.style.color=ok?'#286143':'#87362f'}catch(e){S.location=null;txt.textContent='位置情報を確認できませんでした。位置情報の許可を確認してください。'}finally{btn.disabled=false;renderForm()}}
async function boot(){const gen=++S.generation;S.slot=null;S.day=null;S.health=null;S.canCreate=false;S.location=null;status('LINE接続と営業カレンダーを確認しています…');renderForm();try{await waitForLine();const day=await D.getCurrent({force:true});if(gen!==S.generation)return;S.day=day;const dayEl=$('recDay');dayEl.innerHTML=`<span><small>${esc(fmtDate(day.operationalDate))} の営業</small><strong>${esc(day.businessType)}</strong></span><b>${esc(day.isClosed?'休館':day.durationLabel)}</b>`;if(day.isClosed){status('本日は休館日です。','bad');S.slots=[];renderSlots();renderForm();return}let waitTypes=null;if(backendReady()){try{const [h,w]=await Promise.all([jsonp('health'),jsonp('waitTypes')]);S.health=h;waitTypes=w&&w.ok&&Array.isArray(w.waitTypes)?w.waitTypes:null;S.canCreate=E.featureFlags?.receptionCreate===true&&healthSupportsOfficialDevelop(h)}catch(e){console.warn('new gateway read unavailable',e)}}S.slots=buildSlots(waitTypes);renderSlots();renderForm();if(S.canCreate)status('LINE本人確認・営業日・Gateway接続を確認しました。受付できます。','ok');else status('受付画面は新HOMEへ統合済みです。現在は安全な新Gatewayの接続前なので、最終確定だけ停止しています。','warn')}catch(e){status(String(e?.message||e),'bad');S.slots=[];renderSlots();renderForm()}}
function saveConfirmed(rec){try{localStorage.setItem(CACHE_KEY,JSON.stringify({...rec,cachedAt:Date.now()}));localStorage.setItem(CALL_KEY,JSON.stringify({businessDate:rec.businessDate,receiptNo:String(rec.receiptNo),cachedAt:Date.now()}))}catch{}}
function lockAmbiguous(){S.locked=true;S.busy=false;const result=$('recResult');result.hidden=false;result.innerHTML='<div class="rec-lock"><strong>受付結果を確認しています。新しい受付は行わないでください。</strong><br>AirWAIT側だけ受付が成立している可能性があります。自動再送は停止しました。</div>';status('受付結果が不明なため、安全のため再受付をロックしました。','bad');renderForm()}
async function submit(){if($('recSubmit')?.disabled||S.busy||S.locked||!S.slot||!S.day||!S.canCreate)return;S.busy=true;renderForm();try{const latest=await D.getCurrent({force:true});if(latest.operationalDate!==S.day.operationalDate)throw Error('営業日が切り替わりました。もう一度確認してください。');if(S.mode==='onsite'&&!locationOk())throw Error('現在地の確認が必要です。');const token=String(liff.getAccessToken()||'');if(token.length<20)throw Error('LINE本人確認情報を取得できません。');const loc=S.location||{};const r=await post('createReservation',{mode:S.mode,adults:S.adult,paidChildren:S.child,infants:S.infant,waitTypeId:S.slot.waitTypeId,operationalDate:S.day.operationalDate,liffAccessToken:token,latitude:loc.lat||'',longitude:loc.lng||'',accuracy:loc.accuracy||'',locationTimestamp:loc.timestamp||''});if(r?.ambiguous||/AMBIGUOUS|RESULT_UNKNOWN|MANUAL_REVIEW/.test(String(r?.error||r?.message||''))){lockAmbiguous();return}if(!(r&&r.ok&&r.stored&&r.receiptNo&&r.reserveId&&String(r.businessDate||'')===S.day.operationalDate))throw Error(String(r?.error||'受付結果が不正です。'));const rec={reserveId:r.reserveId,receiptNo:r.receiptNo,shortUrl:String(r.shortUrl||''),businessDate:S.day.operationalDate,businessType:S.day.businessType,mode:S.mode,waitTypeId:S.slot.waitTypeId,waitTypeLabel:S.slot.label,adults:S.adult,paidChildren:S.child,infants:S.infant,totalPeople:total(),totalPrice:price(),source:'asoboon-miniapp-v2-develop'};saveConfirmed(rec);const result=$('recResult');result.hidden=false;result.innerHTML=`<div class="rec-result"><strong>${esc(rec.receiptNo)}</strong><span>受付番号 / 受付が完了しました</span></div>`;status('受付が完了しました。','ok');S.busy=false;renderForm()}catch(e){if(e?.ambiguous){lockAmbiguous();return}S.busy=false;status(String(e?.message||e),'bad');renderForm()}}
function setMode(mode){S.mode=mode==='onsite'?'onsite':'web';S.slot=null;S.location=null;S.slots=buildSlots(S.health?.waitTypes||null);renderSlots();renderForm()}
function mount(ctx){CTX=ctx||{};S.generation++;$('recWeb')?.addEventListener('click',()=>setMode('web'));$('recOnsite')?.addEventListener('click',()=>setMode('onsite'));$('recLocationBtn')?.addEventListener('click',checkLocation);$('recAgree')?.addEventListener('change',e=>{S.agree=Boolean(e.target.checked);renderForm()});$('recSubmit')?.addEventListener('click',submit);document.querySelector('.view')?.addEventListener('click',e=>{const slot=e.target.closest?.('[data-rec-slot]');if(slot){S.slot=S.slots.find(x=>String(x.waitTypeId)===String(slot.dataset.recSlot))||null;renderSlots();renderForm();return}const b=e.target.closest?.('[data-rec-k]');if(!b||b.disabled)return;const k=b.dataset.recK,d=Number(b.dataset.recD),prev={adult:S.adult,child:S.child,infant:S.infant};S[k]=Math.max(k==='adult'?1:0,Number(S[k])+d);if(!validPeople())Object.assign(S,prev);renderForm()});renderForm();void boot()}
window.ASOBOON_V2_RECEPTION=Object.freeze({version:'1.0.0',render,mount});
})();
