(()=>{'use strict';
const root=document.getElementById('app');if(!root)return;
const setText=(el,text)=>{if(el&&el.textContent!==text)el.textContent=text};
function state(){const p=new URLSearchParams(location.search);return{view:String(p.get('view')||'home'),panel:String(p.get('panel')||'')}}
function patchHome(){const p=root.querySelector('.v7-call-title p');if(p)setText(p,'呼出後30分以内に、ASOBooN入口へお越しください。')}
function patchCallstatus(){const box=root.querySelector('#csState.calling');if(!box)return;setText(root.querySelector('#csMessage'),'呼出後30分以内に、受付番号を準備してASOBooN入口へお越しください。')}
function patchParking(){const {view,panel}=state();if(view!=='parking'||panel==='info')return;const body=root.querySelector('.pv7-page .pv7-body');if(!body||body.querySelector('.pv7-parking-map'))return;const anchor=body.querySelector('.pv7-callout.blue');const html=`<section class="pv7-section pv7-parking-map"><h2>駐車場・アクセス</h2><div class="pv7-callout green"><strong>駐車料金は無料です。</strong><br>一般道側はイイナパーク川口の駐車場、首都高側は川口PA駐車場をご利用ください。</div><div class="pv7-map-grid"><a class="pv7-maplink recommended" data-external href="https://maps.app.goo.gl/hKcx4SKWdEYZHcPE6?g_st=ic" target="_blank" rel="noopener noreferrer"><span><strong>一般道から</strong><small>東門駐車場①・比較的近くておすすめ</small></span><b>最短 ↗</b></a><a class="pv7-maplink" data-external href="https://maps.app.goo.gl/wnq7keJLpMDo6GrC8?g_st=ic" target="_blank" rel="noopener noreferrer"><span><strong>一般道から</strong><small>正門駐車場①・距離はあるが台数多め</small></span><b>地図 ↗</b></a><a class="pv7-maplink highway" data-external href="https://maps.app.goo.gl/PE7zNw8WGpkhvbBZ6?g_st=ic" target="_blank" rel="noopener noreferrer"><span><strong>首都高から</strong><small>川口PA駐車場・ハイウェイオアシスへ直結</small></span><b>地図 ↗</b></a></div><p class="pv7-map-note">一般道側駐車場 9:00〜18:00 / 川口PA側 24時間</p></section><section class="pv7-section pv7-contact"><h2>お問い合わせ</h2><p>受付や来場について確認が必要な場合は、ASOBooNへお電話ください。</p><a class="pv7-phone" data-external href="tel:0484209780">048-420-9780へ電話</a></section>`;if(anchor)anchor.insertAdjacentHTML('beforebegin',html);else body.insertAdjacentHTML('beforeend',html)}
function patch(){patchHome();patchCallstatus();patchParking()}
new MutationObserver(()=>queueMicrotask(patch)).observe(root,{subtree:true,childList:true,characterData:true});window.addEventListener('popstate',()=>setTimeout(patch,0));patch();setTimeout(patch,80);setTimeout(patch,350);
})();
