(()=>{'use strict';
const root=document.getElementById('app');if(!root)return;
let queued=false;
function route(){const p=new URLSearchParams(location.search);return{view:String(p.get('view')||'home'),panel:String(p.get('panel')||'')}}
function parkingSvg(){return '<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M7 20V4h7a5 5 0 0 1 0 10H7" stroke="currentColor" stroke-width="2" stroke-linecap="round"/><path d="M7 14h7" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>'}
function patchHome(){if(route().view!=='home')return;const guide=root.querySelector('.v7-guide');if(guide&&!guide.querySelector('.v12-home-parking')){guide.insertAdjacentHTML('beforeend',`<button class="v7-guide-row v12-home-parking" type="button" data-v7-view="parking"><span class="v7-guide-icon">${parkingSvg()}</span><span class="v7-guide-copy"><strong>駐車場・アクセス</strong><small>一般道・首都高からの行き方</small></span><span class="v7-chev">›</span></button>`)}const more=root.querySelector('.v7-more');if(more){more.dataset.v7View='parking';more.dataset.v7Panel='info';const first=more.querySelector('span');if(first&&first.textContent!=='その他のご案内')first.textContent='その他のご案内'}}
function patchFirst(){const s=route();if(s.view!=='first'||s.panel)return;const body=root.querySelector('.pv7-page .pv7-body');if(!body||body.querySelector('.v12-first-locker'))return;const flow=body.querySelector('.pv7-timeline')?.closest('.pv7-section');const html='<div class="v12-first-locker"><strong>ロッカー：</strong>受付・会計時に、1回のお会計につきロッカーを1つ貸し出します。</div>';if(flow)flow.insertAdjacentHTML('afterend',html);else body.insertAdjacentHTML('beforeend',html)}
function patchEntry(){if(route().view!=='entry')return;const body=root.querySelector('.pv7-page .pv7-body');if(!body)return;const road=body.querySelector('.pv7-roadflow');if(road){const steps=road.querySelectorAll('.pv7-roadstep');const step4=steps[3]?.querySelector('small');if(step4&&step4.textContent!=='受付番号をスタッフへお見せください。会計後、1回のお会計につきロッカーを1つ貸し出します。')step4.textContent='受付番号をスタッフへお見せください。会計後、1回のお会計につきロッカーを1つ貸し出します。';if(!body.querySelector('.v12-practical'))road.insertAdjacentHTML('afterend',`<section class="v12-practical"><h2>入場後のご案内</h2><div class="v12-info-card orange"><span class="v12-info-icon">▣</span><div><strong>ロッカー</strong><p>1回のお会計につき、ロッカーを1つ貸し出します。</p></div></div><div class="v12-info-card green"><span class="v12-info-icon">↔</span><div><strong>一時退場について</strong><p>一時退場については、退場前にスタッフへお声がけください。再入場の可否・方法をスタッフがご案内します。</p></div></div></section>`)}}
function parkingPage(){return `<section class="page-card pv7-page v12-parking-page"><div class="pv7-head"><span class="pv7-eyebrow">駐車場・アクセス</span><h1>どちらから来ますか？</h1><p>一般道側と首都高側で駐車場が異なります。</p></div><div class="pv7-body"><div class="v12-free">P 駐車料金無料</div><p class="v12-parking-intro">一般道からはイイナパーク川口の駐車場、首都高からは川口PA駐車場をご利用ください。</p><section class="pv7-parking-map v12-route-grid"><article class="v12-route-card general"><div class="v12-route-head"><strong>一般道から</strong><span>9:00〜18:00</span></div><p>イイナパーク川口側から入場します。近さを優先するなら東門側がおすすめです。</p><a class="v12-maplink recommended" data-external href="https://maps.app.goo.gl/hKcx4SKWdEYZHcPE6?g_st=ic" target="_blank" rel="noopener noreferrer"><span><strong>東門駐車場①</strong><small>比較的近くておすすめ</small></span><b>最短 ↗</b></a><a class="v12-maplink" data-external href="https://maps.app.goo.gl/wnq7keJLpMDo6GrC8?g_st=ic" target="_blank" rel="noopener noreferrer"><span><strong>正門駐車場①</strong><small>距離はあるが台数多め</small></span><b>地図 ↗</b></a></article><article class="v12-route-card highway"><div class="v12-route-head"><strong>首都高から</strong><span>24時間</span></div><p>川口PA駐車場から川口ハイウェイオアシスへ直接つながります。</p><a class="v12-maplink highway" data-external href="https://maps.app.goo.gl/PE7zNw8WGpkhvbBZ6?g_st=ic" target="_blank" rel="noopener noreferrer"><span><strong>川口PA駐車場</strong><small>ハイウェイオアシスへ直結</small></span><b>地図 ↗</b></a></article></section><p class="v12-parking-note">Googleマップは外部ページで開きます。</p><button class="pv7-secondary-btn" type="button" data-pv7-view="parking" data-pv7-panel="info">営業時間・お問い合わせなどを見る</button></div></section>`}
function patchParking(){const s=route();if(s.view!=='parking'||s.panel==='info')return;const main=root.querySelector('main.view');if(!main||main.querySelector('.v12-parking-page'))return;main.innerHTML=parkingPage();main.dataset.pv7Key='parking:info'}
function patchInfo(){const s=route();if(s.view!=='parking'||s.panel!=='info')return;const body=root.querySelector('.pv7-page .pv7-body');if(!body||body.querySelector('.v12-info-contact'))return;body.insertAdjacentHTML('beforeend',`<section class="pv7-section v12-info-contact"><h2>お問い合わせ</h2><p>受付や来場について確認が必要な場合は、ASOBooNへお電話ください。</p><a class="pv7-phone" data-external href="tel:0484209780">048-420-9780へ電話</a></section><button class="pv7-text-btn" type="button" data-pv7-view="parking">駐車場・アクセスを見る</button>`)}
function patch(){queued=false;patchHome();patchFirst();patchEntry();patchParking();patchInfo()}
function queue(){if(queued)return;queued=true;queueMicrotask(patch)}
new MutationObserver(queue).observe(root,{childList:true,subtree:true,characterData:true});window.addEventListener('popstate',()=>setTimeout(patch,0));patch();setTimeout(patch,80);setTimeout(patch,350);
})();
