(()=>{'use strict';
const E=window.ASOBOON_V2_ENV||{},F=E.featureFlags||{},D=window.ASOBOON_V2_BUSINESS_DAY||{},R=window.ASOBOON_V2_RULES||{},root=document.getElementById('app');if(!root)return;
const RES_KEY='asoboon_v2_current_reservation_develop_v1';
const COPY={ja:{loading:'読み込み中',today:'今日のASOBooN',hours:'利用時間',close:'閉館',guide:'利用案内',fun:'ASOBooNを楽しむ',first:'初めての方',firstSub:'受付から入場まで',price:'料金',priceSub:'大人600円・子ども900円',parking:'アクセス',parkingSub:'駐車場・行き方',rules:'館内ルール',rulesSub:'遊ぶ前に確認',entry:'一時退場・再入場',entrySub:'外出するときはこちら',game:'ミニゲーム',fortune:'おみくじ',stamp:'スタンプ',soon:'準備中'}};
const T=COPY.ja,icons={ticket:'<path d="M5 7.5A2.5 2.5 0 0 0 7.5 5h9A2.5 2.5 0 0 0 19 7.5v1a2.5 2.5 0 0 0 0 5v1A2.5 2.5 0 0 0 16.5 17h-9A2.5 2.5 0 0 0 5 14.5v-1a2.5 2.5 0 0 0 0-5z"/><path d="M12 7v10"/>',queue:'<circle cx="8" cy="8" r="2.5"/><circle cx="16" cy="8" r="2.5"/><path d="M3.5 18c.5-3.5 2-5 4.5-5s4 1.5 4.5 5M12 14c1-.8 2-1 3.3-1 2.7 0 4.3 1.6 4.7 5"/>',bell:'<path d="M6 16h12l-1.5-2v-3a4.5 4.5 0 0 0-9 0v3zM10 19h4"/>',clock:'<circle cx="12" cy="12" r="8"/><path d="M12 7v5l3 2"/>',person:'<circle cx="12" cy="8" r="3"/><path d="M6 20c.4-4 2.4-6 6-6s5.6 2 6 6"/>',yen:'<path d="m7 5 5 7 5-7M8 12h8M8 15h8M12 12v7"/>',parking:'<rect x="4" y="4" width="16" height="16" rx="3"/><path d="M9 17V7h4a3 3 0 0 1 0 6H9"/>',check:'<path d="M7 4h10v16H7zM9 9l1.5 1.5L14 7M9 15h6"/>',door:'<path d="M5 20V4h11v16M9 12h10M16 9l3 3-3 3"/>',game:'<path d="M7 9h10l3 7a2 2 0 0 1-3 2l-2-2H9l-2 2a2 2 0 0 1-3-2zM8 12v3M6.5 13.5h3M16 12h.01M18 14h.01"/>',fortune:'<path d="M7 4h10v16H7zM9 7h6M10 11h4M9 16h6"/>',stamp:'<path d="M8 12h8l2 5H6zM9 20h6M9 12l1-7h4l1 7"/>',alert:'<path d="M12 4 3.5 19h17zM12 9v4M12 16h.01"/>',arrow:'<path d="m9 6 6 6-6 6"/>'};
const svg=k=>`<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round">${icons[k]||icons.check}</svg>`;
const CROWD_SETTINGS=Object.freeze({CAPACITY:350,CROWD_BASE:310,IDS:Object.freeze({'平日特定日':Object.freeze(['0036','0038']),'土日祝日':Object.freeze(['0030','0032','0034'])}),LEVELS:Object.freeze([{max:39,label:'空いています'},{max:59,label:'比較的空いています'},{max:79,label:'やや混雑'},{max:94,label:'混雑しています'},{max:100,label:'かなり混雑しています'}])});
let latest=window.ASOBOON_HOME_STATUS_SNAPSHOT||null,day=null,dayError='',dayLoading=false,lastHero='',crowdSlots=null,crowdError='',crowdAt=0,crowdLoading=false;
const params=()=>new URLSearchParams(location.search),currentView=()=>String(params().get('view')||'home'),feature=n=>F[n]===true,esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])),setText=(el,text)=>{if(el&&el.textContent!==text)el.textContent=text};
function nowJst(){const p=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date()).map(x=>[x.type,x.value]));return{date:`${p.year}-${p.month}-${p.day}`,minutes:Number(p.hour)*60+Number(p.minute)}}
function clockMinutes(v){const m=String(v||'').match(/^(\d{1,2}):(\d{2})$/);return m?Number(m[1])*60+Number(m[2]):NaN}
function availability(){if(dayError)return{type:'error',title:'営業情報を取得できません',message:'受付画面からお進みください。'};if(!day)return{type:'loading',title:T.loading,message:'営業情報を取得しています。'};const now=nowJst();if(String(day.operationalDate||'')!==now.date)return{type:'ended',title:'本日の営業は終了しました',message:'次の営業日にお待ちしています。'};if(day.isClosed)return{type:'closed',title:'本日は休館日です',message:'次の営業日にお待ちしています。'};const close=clockMinutes(day.closingTime);if(Number.isFinite(close)&&now.minutes>=close)return{type:'ended',title:'本日の営業は終了しました',message:'次の営業日にお待ちしています。'};if(String(day.businessType||'')==='平日')return{type:'onsite',title:'本日は現地受付です',message:'ASOBooN入口へお越しください。'};if(now.minutes<420)return{type:'before',title:'LINE当日受付は7:00から',message:'開始までお待ちください。'};return{type:'open'}}
function round5(x){return Math.max(5,Math.round(x/5)*5)}function eta(n){if(n<=5)return'まもなく';const c=Math.max(1,n*.30);if(c<=4)return'約5分以内';let lo=round5(c*.83),hi=round5(c*1.17);if(hi<=lo)hi=lo+5;return`約${lo}〜${hi}分`}
function action(view,label,tone='neutral'){return `<button class="v38-action ${tone}" type="button" data-v7-view="${view}"><span>${label}</span>${svg('arrow')}</button>`}
function guide(kind,title,sub,view,panel=''){return `<button class="v38-guide-card ${kind}" type="button" data-v7-view="${view}"${panel?` data-v7-panel="${panel}"`:''}><span class="v38-icon">${svg(kind)}</span><span><strong>${title}</strong><small>${sub}</small></span>${svg('arrow')}</button>`}
function fun(kind,title,view){const enabled=feature(view);return `<button class="v38-fun-card ${kind}" type="button" data-v7-view="${view}" ${enabled?'':'disabled'}><span class="v38-fun-icon">${svg(kind)}</span><strong>${title}</strong><small>${enabled?'開く':T.soon}</small></button>`}
function baseHome(){return `<section class="home-shell v38-home" aria-label="ASOBooN HOME"><section id="v38Hero" class="v38-hero loading"><div class="v38-hero-icon">${svg('clock')}</div><div><h1>${T.loading}</h1><p>少しお待ちください。</p></div></section><section class="v38-today-section"><h2>${T.today}</h2><button id="v38Today" class="v38-today" type="button" data-v7-view="timeguide" aria-label="本日の営業と利用時間"><span>${svg('clock')}<small>営業</small><strong>${T.loading}</strong></span><span><small>${T.hours}</small><strong>—</strong></span><span><small>${T.close}</small><strong>—</strong></span>${svg('arrow')}</button><section id="v38Slots" class="v38-slots" aria-live="polite"></section></section><section id="v38InUse" class="v38-in-use" hidden><h2>利用中に必要</h2><p>利用時間と一時退場は、上の「ご利用中」から開けます。</p></section><section class="v38-guide"><h2>${T.guide}</h2><div class="v38-guide-grid">${guide('person',T.first,T.firstSub,'first')}${guide('yen',T.price,T.priceSub,'first','price')}${guide('parking',T.parking,T.parkingSub,'parking')}${guide('check',T.rules,T.rulesSub,'rules')}</div>${guide('door',T.entry,T.entrySub,'entry')}</section><section class="v38-fun"><h2>${T.fun}</h2><a class="v38-event" href="https://www.instagram.com/asoboon425/" target="_blank" rel="noopener noreferrer" data-external><span class="v38-fun-icon">${svg('clock')}</span><span><strong>今日のイベント</strong><small>Instagramで見る</small></span>${svg('arrow')}</a><div>${fun('game',T.game,'game')}${fun('fortune',T.fortune,'omikuji')}${fun('stamp',T.stamp,'stamp')}</div></section><section class="v38-help"><details><summary><span>${svg('check')}<strong>よくある質問・困ったとき</strong></span>${svg('arrow')}</summary><div><p><b>呼出後30分を過ぎそうなとき</b><br>受付番号を確認し、ASOBooN入口のスタッフへお声がけください。</p><p><b>受付を取り消したいとき</b><br>呼出状況から受付内容を確認してください。</p><p><b>料金・支払い・再入場</b><br>上の利用案内から詳しく確認できます。</p></div></details></section></section>`}
function fmtDate(value){const raw=String(value||'').trim(),m=raw.match(/^(\d{4})-(\d{2})-(\d{2})$/);if(!m)return raw||'—';return `${Number(m[2])}月${Number(m[3])}日`}
function reservationInfo(receipt=''){let rec=null;try{rec=JSON.parse(localStorage.getItem(RES_KEY)||'null')}catch{}if(!rec)return null;if(receipt&&rec.receiptNo&&String(rec.receiptNo)!==String(receipt))return null;return rec}
function peopleBreakdown(rec){if(!rec)return'—';const a=Number(rec.adults),c=Number(rec.paidChildren),i=Number(rec.infants);if(![a,c,i].every(Number.isFinite))return'—';const parts=[`おとな ${a}名`];if(c>0)parts.push(`こども ${c}名`);if(i>0)parts.push(`0〜5か月 ${i}名`);return parts.join('・')}
function reservationCard(receipt=''){const rec=reservationInfo(receipt),number=String(receipt||rec?.receiptNo||'—'),date=fmtDate(rec?.businessDate||'—'),people=peopleBreakdown(rec);return `<div class="v38-reservation-card" aria-label="受付情報"><div class="v38-reservation-item receipt"><small>受付番号</small><strong>${esc(number)}</strong></div><div class="v38-reservation-item"><small>利用日</small><strong>${esc(date)}</strong></div><div class="v38-reservation-item people"><small>人数内訳</small><strong>${esc(people)}</strong></div></div>`}
function stateLabel(text){return `<div class="v38-state-label">${esc(text)}</div>`}
function heroMarkup(data={}){const kind=String(data.kind||'sync'),receipt=String(data.receipt||'').trim();if(kind==='error')return{kind:'error',html:`<div class="v38-hero-icon">${svg('alert')}</div><div class="v38-hero-body"><h1>受付状況を取得できません</h1><p>呼出状況からもう一度お試しください。</p>${receipt?reservationCard(receipt):''}${action('callstatus','呼出状況を見る')}</div>`};if(kind==='waiting'){const n=Number(data.ahead);if(!Number.isFinite(n))return heroMarkup({kind:'error',receipt});const proximity=n<=3?'ready':n<=5?'near':n<=10?'closer':n>=20?'far':'steady';return{kind:`waiting ${proximity}`,html:`<div class="v38-hero-icon">${svg('queue')}</div><div class="v38-hero-body">${stateLabel('呼出前')}<h1>順番をお待ちください</h1><div class="v38-ahead"><small>あと</small><strong>${n}</strong><span>組</span></div><div class="v38-eta">${eta(n)}</div>${reservationCard(receipt)}${action('callstatus','詳しく見る')}</div>`}}if(kind==='calling')return{kind:'calling',html:`<div class="v38-hero-icon">${svg('bell')}</div><div class="v38-hero-body">${stateLabel('呼出中')}<h1>ご入場可能です</h1><p>受付番号をご準備のうえ、ASOBooN入口へお越しください。</p><div class="v38-deadline">呼出から30分以内</div>${reservationCard(receipt)}${action('callstatus','受付番号を見る','calling')}</div>`};if(kind==='hold')return{kind:'hold',html:`<div class="v38-hero-icon">${svg('alert')}</div><div class="v38-hero-body">${stateLabel('保留')}<h1>受付でご確認ください</h1><p>受付番号をご準備のうえ、ASOBooN入口でご確認ください。</p>${reservationCard(receipt)}${action('callstatus','呼出状況を見る')}</div>`};if(kind==='guided'||kind==='guide')return{kind:'guided',html:`<div class="v38-hero-icon">${svg('check')}</div><div class="v38-hero-body">${stateLabel('案内済み')}<h1>ご入場済みです</h1><p>ASOBooNをお楽しみください。</p>${reservationCard(receipt)}<div class="v38-inline-actions">${action('timeguide','何時まで遊べる')}${action('entry','一時退場・再入場')}</div></div>`};if(kind==='canceled'||(kind==='none'&&data.canceled)){const a=availability();return{kind:'canceled',html:`<div class="v38-hero-icon">${svg('alert')}</div><div class="v38-hero-body">${stateLabel('取り消し')}<h1>受付が取り消されました</h1><p>呼び出しから30分以上経過したためです。</p>${reservationCard(receipt)}${a.type==='open'?action('reception','もう一度受付する','primary'):''}</div>`}}if(kind==='none'){const a=availability();if(a.type==='open')return{kind:'open',html:`<div class="v38-hero-icon">${svg('ticket')}</div><div class="v38-hero-body"><h1>当日受付</h1><p>利用する回と人数を選びます。</p>${action('reception','順番を取る','primary')}</div>`};return{kind:a.type,html:`<div class="v38-hero-icon">${svg(a.type==='error'?'alert':'clock')}</div><div class="v38-hero-body"><h1>${esc(a.title)}</h1><p>${esc(a.message)}</p>${action('first','利用案内へ')}</div>`}}return{kind:'sync',html:`<div class="v38-hero-icon">${svg('clock')}</div><div class="v38-hero-body"><h1>${T.loading}</h1><p>${esc(data.message||'少しお待ちください。')}</p>${receipt?action('callstatus','詳しく見る'):''}</div>`}}
function renderHero(data={}){const el=root.querySelector('#v38Hero');if(!el)return;const v=heroMarkup(data),sig=JSON.stringify([v.kind,data.receipt,data.ahead,data.canceled,data.message,day?.operationalDate,day?.closingTime,dayError]);if(sig===lastHero&&el.dataset.rendered==='1')return;lastHero=sig;el.dataset.rendered='1';el.className=`v38-hero ${v.kind}`;el.innerHTML=v.html;document.body.classList.remove('v38-state-waiting','v38-state-calling','v38-state-guided','v38-state-hold','v38-state-canceled');const theme=String(v.kind).split(/\s+/)[0];if(['waiting','calling','guided','hold','canceled'].includes(theme))document.body.classList.add(`v38-state-${theme}`);const inUse=root.querySelector('#v38InUse');if(inUse)inUse.hidden=!['guided','guide'].includes(String(data.kind||''))}
function patchToday(){const box=root.querySelector('#v38Today');if(!box)return;const labels=box.querySelectorAll('small'),vals=box.querySelectorAll('strong');if(day){setText(vals[0],day.isClosed?'休館':day.businessType||'—');setText(vals[1],day.isClosed?'—':day.durationLabel||'—');setText(vals[2],day.isClosed?'—':day.closingTime||'—');box.classList.toggle('closed',Boolean(day.isClosed));return}setText(vals[0],dayError?'取得できません':T.loading);setText(vals[1],'—');setText(vals[2],'—')}
function crowdMetric(value){const n=Number(value);if(!Number.isSafeInteger(n)||n<0||n>CROWD_SETTINGS.CAPACITY)return null;const current=Math.max(CROWD_SETTINGS.CAPACITY-n,0),percent=Math.min(100,Math.floor(current/CROWD_SETTINGS.CROWD_BASE*100));const tone=percent<=39?'low':percent<=59?'light':percent<=79?'mid':percent<=94?'high':'very-high';return{percent,level:CROWD_SETTINGS.LEVELS.find(x=>percent<=x.max)?.label||'かなり混雑しています',tone}}
function crowdTime(name){const m=String(name||'').normalize('NFKC').match(/^(\d{1,2})時(半|(?:([0-5]?\d)分)?)/);if(!m)return'';const hour=Number(m[1]),minute=m[2]==='半'?30:Number(m[3]||0);return hour<=23?`${String(hour).padStart(2,'0')}:${String(minute).padStart(2,'0')}`:''}
function validCrowdSlots(){const ids=new Set(CROWD_SETTINGS.IDS[String(day?.businessType||'')]||[]);return(Array.isArray(crowdSlots)?crowdSlots:[]).filter(x=>ids.has(String(x?.waitTypeId||''))&&x?.reserveUnit==='PERSON'&&x?.evidence==='PERSON'&&String(x?.waitTypeName||'').normalize('NFKC').replace(/\s+/g,'')===String(x?.detailedWaitType||'').normalize('NFKC').replace(/\s+/g,'')&&crowdMetric(x?.remaining)&&crowdTime(x?.waitTypeName))}
function renderSlots(){const box=root.querySelector('#v38Slots');if(!box)return;if(!day||dayError||day.isClosed){box.innerHTML=dayError?'<h3>本日の混雑状況</h3><p class="v38-slots-error">混雑情報を取得できません</p>':'';return}if(String(day.businessType)==='平日'){box.innerHTML='<h3>本日の混雑状況</h3><p class="v38-slots-note">現地受付日の混雑目安は現在準備中です。</p>';return}if(crowdLoading&&!crowdSlots){box.innerHTML='<h3>本日の混雑状況</h3><p class="v38-slots-note">混雑情報を取得しています…</p>';return}const slots=validCrowdSlots();if(crowdError||!slots.length){box.innerHTML='<h3>本日の混雑状況</h3><p class="v38-slots-error">混雑情報を取得できません</p>';return}const rows=slots.map(slot=>{const m=crowdMetric(slot.remaining),time=crowdTime(slot.waitTypeName);return `<article class="v38-crowd-card crowd-${m.tone}"><div class="v38-crowd-head"><time>${esc(time)}回</time><span>混雑目安</span></div><div class="v38-crowd-value"><strong>${m.percent}<small>%</small></strong><em>${esc(m.level)}</em></div><div class="v38-crowd-remaining"><span>受付残り</span><strong>${slot.remaining}<small>名</small></strong></div><div class="v38-crowd-track" role="progressbar" aria-label="${esc(time)}回の混雑目安" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${m.percent}"><span style="width:${m.percent}%"></span></div></article>`}).join('');box.innerHTML=`<h3>本日の混雑状況</h3><p class="v38-crowd-note">受付状況をもとにした目安です。館内の滞在人数ではありません。</p><div class="v38-crowd-list">${rows}</div>`}
function mount(){if(currentView()!=='home'){document.body.classList.remove('v38-home-active');return}if(!root.querySelector('.v38-home')){const old=root.querySelector('.home-shell');if(!old)return;old.outerHTML=baseHome()}document.body.classList.remove('v35-home-active','v37-home-active');document.body.classList.add('v38-home-active');const brand=document.querySelector('.brand small');setText(brand,'川口ハイウェイオアシス');patchToday();renderSlots();if(!latest&&window.ASOBOON_HOME_STATUS_SNAPSHOT)latest=window.ASOBOON_HOME_STATUS_SNAPSHOT;renderHero(latest||{kind:'sync'})}
async function fetchCrowd(force=false){if(crowdLoading)return;if(!force&&crowdSlots&&!crowdError&&Date.now()-crowdAt<60000)return;crowdLoading=true;crowdError='';if(currentView()==='home')renderSlots();const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),8000);try{const url=new URL(E.backendUrl);url.searchParams.set('action','crowdRemaining');const response=await fetch(url,{cache:'no-store',signal:controller.signal});const data=await response.json();if(!response.ok||data?.ok!==true||!Array.isArray(data.slots))throw Error(String(data?.error||'CROWD_UNAVAILABLE'));crowdSlots=data.slots;crowdAt=Date.now();crowdError=''}catch(e){crowdSlots=null;crowdError=String(e?.message||e||'CROWD_UNAVAILABLE')}finally{clearTimeout(timer);crowdLoading=false;if(currentView()==='home')renderSlots()}}
async function refreshDay(force=false){if(dayLoading||typeof D.getCurrent!=='function')return;dayLoading=true;dayError='';try{day=await Promise.race([D.getCurrent({force}),new Promise((_,reject)=>setTimeout(()=>reject(Error('BUSINESS_DAY_HOME_TIMEOUT')),4500))]);if(!day?.ok)throw Error('BUSINESS_DAY_UNAVAILABLE');if(!day.isClosed&&['平日特定日','土日祝日'].includes(String(day.businessType||'')))await fetchCrowd(force);else{crowdSlots=null;crowdError='';crowdAt=0}}catch(e){day=null;dayError=String(e?.message||e||'BUSINESS_DAY_UNAVAILABLE')}finally{dayLoading=false;if(currentView()==='home'){lastHero='';patchToday();renderSlots();renderHero(latest||{kind:'none'})}}}
window.addEventListener('asoboon:v8-home-status',e=>{latest=e.detail||{kind:'sync'};if(currentView()==='home'){lastHero='';mount()}});window.addEventListener('asoboon:v2-route-rendered',()=>{lastHero='';mount()});window.addEventListener('focus',()=>{if(currentView()==='home')void refreshDay(false)});document.addEventListener('visibilitychange',()=>{if(!document.hidden&&currentView()==='home')void refreshDay(false)});mount();void refreshDay(false);
})();
