(()=>{'use strict';
const E=window.ASOBOON_V2_ENV||{};
const F=E.featureFlags||{};
const root=document.getElementById('app');
if(!root)return;
let lastSignature='',latestStatus=window.ASOBOON_HOME_STATUS_SNAPSHOT||null;
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const currentView=()=>String(new URLSearchParams(location.search).get('view')||'home');
const feature=name=>F[name]===true;
function round5(x){return Math.max(5,Math.round(x/5)*5)}
function etaText(n){if(n<=5)return'まもなく';const center=Math.max(1,n*.30);if(center<=4)return'約5分以内';let lo=round5(center*.83),hi=round5(center*1.17);if(hi<=lo)hi=lo+5;return`約${lo}〜${hi}分`}
function icon(kind){const map={first:'<svg viewBox="0 0 24 24" fill="none"><circle cx="12" cy="8" r="3" stroke="currentColor" stroke-width="2"/><path d="M6 20c.4-4 2.4-6 6-6s5.6 2 6 6" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>',price:'<svg viewBox="0 0 24 24" fill="none"><path d="M5 5h14v14H5z" stroke="currentColor" stroke-width="2"/><path d="M8 9h8M8 13h8M8 17h5" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>',entry:'<svg viewBox="0 0 24 24" fill="none"><path d="M5 20V4h11v16M9 12h10M16 9l3 3-3 3" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>',rules:'<svg viewBox="0 0 24 24" fill="none"><path d="M7 4h10v16H7z" stroke="currentColor" stroke-width="2"/><path d="m9 9 1.5 1.5L14 7M9 15h6" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>',parking:'<svg viewBox="0 0 24 24" fill="none"><rect x="4" y="4" width="16" height="16" rx="3" stroke="currentColor" stroke-width="2"/><path d="M9 17V7h4a3 3 0 0 1 0 6H9" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>',time:'<svg viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="8" stroke="currentColor" stroke-width="2"/><path d="M12 8v5l3 2" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>',more:'<svg viewBox="0 0 24 24" fill="none"><circle cx="6" cy="12" r="1.5" fill="currentColor"/><circle cx="12" cy="12" r="1.5" fill="currentColor"/><circle cx="18" cy="12" r="1.5" fill="currentColor"/></svg>'};return map[kind]||''}
function guideRow(kind,label,sub,view,panel=''){return `<button class="v32-guide-row" type="button" data-v7-view="${view}"${panel?` data-v7-panel="${panel}"`:''}><span class="v32-guide-icon">${icon(kind)}</span><span class="v32-guide-copy"><strong>${label}</strong><small>${sub}</small></span><span class="v32-chev">›</span></button>`}
function baseHome(){return `<section class="home-shell v7-home v32-home"><div id="v7Hero" class="v32-hero v32-neutral"><div class="v32-state-label">確認中</div><h1>受付状況を確認しています</h1><p>最新の受付状況を確認しています。</p></div><section id="v7Today" class="v7-today" aria-label="本日の営業"><div><small>本日の営業</small><strong>確認中</strong></div><div><small>利用時間</small><strong>—</strong></div><div><small>閉館</small><strong>—</strong></div></section><section class="v32-section"><div class="v32-section-head"><small>ASOBooN GUIDE</small><h2>利用案内</h2></div><div class="v32-guide">${guideRow('time','何時まで遊べる？','本日の利用時間・閉館時間','timeguide')}${guideRow('first','初めての方','当日受付から入場まで','first')}${guideRow('price','料金','料金・お支払い','first','price')}${guideRow('entry','入場・退場','入場・一時退場・再入場','entry')}${guideRow('rules','館内ルール','安全に遊ぶためのご案内','rules')}${guideRow('parking','駐車場・アクセス','一般道・高速道路から','parking')}${guideRow('more','その他のご案内','よくあるご案内はこちら','parking','info')}</div></section><section class="v32-play"><div class="v32-section-head"><small>FUN</small><h2>お楽しみ</h2></div><div class="v7-play-row"><button class="v7-play-item" type="button" data-v7-view="game" ${feature('game')?'':'disabled'}><span class="v7-play-icon">▣</span>ミニゲーム${feature('game')?'':'<small>準備中</small>'}</button><button class="v7-play-item" type="button" data-v7-view="omikuji" ${feature('omikuji')?'':'disabled'}><span class="v7-play-icon">◇</span>おみくじ${feature('omikuji')?'':'<small>準備中</small>'}</button><button class="v7-play-item" type="button" data-v7-view="stamp" ${feature('stamp')?'':'disabled'}><span class="v7-play-icon">◎</span>スタンプ${feature('stamp')?'':'<small>準備中</small>'}</button></div></section></section>`}
function heroMarkup(data={}){const kind=String(data.kind||'sync');if(kind==='waiting'){const n=Number(data.ahead);if(!Number.isFinite(n))return heroMarkup({kind:'sync',receipt:data.receipt,message:'最新の順番を確認しています。'});return{kind,html:`<div class="v32-state-top"><span class="v32-dot"></span><strong>呼出待ち</strong></div><div class="v32-wait-grid"><div class="v32-ahead"><small>あなたの前</small><div><strong>${n}</strong><span>組</span></div></div><div class="v32-eta"><small>待ち時間の目安</small><strong>${etaText(n)}</strong></div></div><p>順番になるとLINEでお知らせします。</p><button class="v32-action dark" type="button" data-v7-view="callstatus">呼出状況を見る <span>›</span></button>`}}
if(kind==='calling')return{kind,html:`<div class="v32-state-label">ただいま呼出中</div><h1>入場できます！</h1><p><strong>呼出後30分以内</strong>にASOBooN入口へお越しください。</p><button class="v32-action green" type="button" data-v7-view="callstatus">受付番号・詳細を見る <span>›</span></button>`};
if(kind==='guide')return{kind,html:`<div class="v32-state-label">ご案内中</div><h1>スタッフのご案内をご確認ください</h1><p>入場・退場の流れはこちらから確認できます。</p><button class="v32-action dark" type="button" data-v7-view="entry">入場・退場の案内を見る <span>›</span></button>`};
if(kind==='none'&&data.canceled)return{kind:'canceled',html:`<div class="v32-state-label">取消済み</div><h1>受付は取消になっています</h1><p>新しく順番を取る場合は、当日受付からお進みください。</p><button class="v32-action dark" type="button" data-v7-view="reception">当日受付をする <span>›</span></button>`};
if(kind==='none')return{kind,html:`<div class="v32-state-label">本日のご利用</div><h1>本日の当日受付</h1><p>利用する回と人数を選んで、LINEで順番を取ります。</p><button class="v32-action orange" type="button" data-v7-view="reception">当日受付をする <span>›</span></button>`};
return{kind:'sync',html:`<div class="v32-state-label">確認中</div><h1>受付状況を確認しています</h1><p>${esc(data.message||'最新の受付状況を確認しています。')}</p>${data.receipt?'<button class="v32-action dark" type="button" data-v7-view="callstatus">呼出状況を確認する <span>›</span></button>':''}`}}
function renderHero(data={}){const hero=root.querySelector('#v7Hero');if(!hero)return;const view=heroMarkup(data);const sig=JSON.stringify([view.kind,data.receipt,data.ahead,data.canceled,data.message]);if(sig===lastSignature&&hero.dataset.v32Rendered==='1')return;lastSignature=sig;hero.dataset.v32Rendered='1';hero.className=`v32-hero v32-${view.kind}`;hero.innerHTML=view.html}
function patchHome(){if(currentView()!=='home'){document.body.classList.remove('v32-home-active');return}const existing=root.querySelector('.v32-home');if(existing){if(!latestStatus&&window.ASOBOON_HOME_STATUS_SNAPSHOT)latestStatus=window.ASOBOON_HOME_STATUS_SNAPSHOT;if(latestStatus)renderHero(latestStatus);return}const old=root.querySelector('.home-shell');if(!old)return;lastSignature='';document.body.classList.add('v32-home-active');const brandSmall=document.querySelector('.brand small');if(brandSmall)brandSmall.textContent='川口ハイウェイオアシス';old.outerHTML=baseHome();if(!latestStatus&&window.ASOBOON_HOME_STATUS_SNAPSHOT)latestStatus=window.ASOBOON_HOME_STATUS_SNAPSHOT;if(latestStatus)renderHero(latestStatus)}
window.addEventListener('asoboon:v8-home-status',e=>{latestStatus=e.detail||{kind:'sync'};if(currentView()==='home')patchHome()});
window.addEventListener('popstate',()=>setTimeout(()=>{lastSignature='';if(window.ASOBOON_HOME_STATUS_SNAPSHOT)latestStatus=window.ASOBOON_HOME_STATUS_SNAPSHOT;patchHome()},0));
new MutationObserver(()=>queueMicrotask(patchHome)).observe(root,{childList:true,subtree:true});
patchHome();setTimeout(patchHome,50);setTimeout(patchHome,300);
})();