(()=>{'use strict';
const E=window.ASOBOON_V2_ENV||{};
const F=E.featureFlags||{};
const D=window.ASOBOON_V2_BUSINESS_DAY||{};
const root=document.getElementById('app');
if(!root)return;
let lastSignature='',latestStatus=window.ASOBOON_HOME_STATUS_SNAPSHOT||null,day=null,dayError='',dayLoading=false;
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const params=()=>new URLSearchParams(location.search);
const currentView=()=>String(params().get('view')||'home');
const feature=name=>F[name]===true;
const setText=(el,text)=>{if(el&&el.textContent!==text)el.textContent=text};
function nowJst(){const p=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date()).map(x=>[x.type,x.value]));return{date:`${p.year}-${p.month}-${p.day}`,minutes:Number(p.hour)*60+Number(p.minute)}}
function clockMinutes(v){const m=String(v||'').match(/^(\d{1,2}):(\d{2})$/);return m?Number(m[1])*60+Number(m[2]):NaN}
function availability(){if(dayError)return{type:'error',tag:'確認中',title:'営業情報を確認できません',message:'受付画面で最新の営業情報をご確認ください。'};if(!day)return{type:'loading',tag:'確認中',title:'本日の営業を確認しています',message:'営業カレンダーを確認しています。'};const now=nowJst();if(String(day.operationalDate||'')!==now.date)return{type:'ended',tag:'受付終了',title:'本日の当日受付は終了しました',message:'次の営業日にご利用ください。'};if(day.isClosed)return{type:'closed',tag:'休館日',title:'本日は休館日です',message:'次の営業日にお待ちしています。'};const close=clockMinutes(day.closingTime);if(Number.isFinite(close)&&now.minutes>=close)return{type:'ended',tag:'受付終了',title:'本日の受付は終了しました',message:'次の営業日にご利用ください。'};const businessType=String(day.businessType||'');if(businessType==='平日'){if(now.minutes<9*60+30)return{type:'onsite-before',tag:'現地受付',title:'通常平日は現地受付です',message:'現地受付は9:30から。ASOBooN入口でご案内します。'};return{type:'onsite',tag:'現地受付',title:'本日は現地受付です',message:'通常平日はLINE当日受付を行っていません。ASOBooN入口で受付してください。'}}if(now.minutes<7*60)return{type:'before',tag:'受付開始前',title:'LINE当日受付は7:00から',message:'オンライン受付対象日は7:00から受付できます。'};return{type:'open'}}
function round5(x){return Math.max(5,Math.round(x/5)*5)}
function etaText(n){if(n<=5)return'まもなく';const center=Math.max(1,n*.30);if(center<=4)return'約5分以内';let lo=round5(center*.83),hi=round5(center*1.17);if(hi<=lo)hi=lo+5;return`約${lo}〜${hi}分`}
function icon(kind){const map={first:'<svg viewBox="0 0 24 24" fill="none"><circle cx="12" cy="8" r="3" stroke="currentColor" stroke-width="2"/><path d="M6 20c.4-4 2.4-6 6-6s5.6 2 6 6" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>',price:'<svg viewBox="0 0 24 24" fill="none"><path d="M5 5h14v14H5z" stroke="currentColor" stroke-width="2"/><path d="M8 9h8M8 13h8M8 17h5" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>',entry:'<svg viewBox="0 0 24 24" fill="none"><path d="M5 20V4h11v16M9 12h10M16 9l3 3-3 3" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>',rules:'<svg viewBox="0 0 24 24" fill="none"><path d="M7 4h10v16H7z" stroke="currentColor" stroke-width="2"/><path d="m9 9 1.5 1.5L14 7M9 15h6" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>',parking:'<svg viewBox="0 0 24 24" fill="none"><rect x="4" y="4" width="16" height="16" rx="3" stroke="currentColor" stroke-width="2"/><path d="M9 17V7h4a3 3 0 0 1 0 6H9" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>',time:'<svg viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="8" stroke="currentColor" stroke-width="2"/><path d="M12 8v5l3 2" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>',info:'<svg viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="8" stroke="currentColor" stroke-width="2"/><path d="M12 11v5M12 8h.01" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>'};return map[kind]||''}
function guideRow(kind,label,sub,view,panel=''){return `<button class="v32-guide-row" type="button" data-v7-view="${view}"${panel?` data-v7-panel="${panel}"`:''}><span class="v32-guide-icon">${icon(kind)}</span><span class="v32-guide-copy"><strong>${label}</strong><small>${sub}</small></span><span class="v32-chev">›</span></button>`}
function guideGroup(title,eyebrow,rows,tone){return `<section class="v32-info-block v32-${tone}"><div class="v32-block-head"><small>${eyebrow}</small><h2>${title}</h2></div><div class="v32-guide">${rows}</div></section>`}
function guideMarkup(){const facility=`${guideRow('price','料金','料金・人数ルール','first','price')}${guideRow('info','営業時間・対象年齢','営業時間・対象年齢など','parking','info')}${guideRow('parking','駐車場・アクセス','一般道・高速道路からのアクセス','parking')}`;const rules=`${guideRow('rules','館内ルール','安全に遊ぶためのご案内','rules')}${guideRow('entry','一時退場・再入場','外出・戻るときのルール','entry')}`;return `${guideGroup('施設について','ABOUT',facility,'facility')}${guideGroup('ご利用ルール','RULES',rules,'rules')}`}
function welcomeMarkup(){return `<button class="v32-welcome" type="button" data-v7-view="first"><span class="v32-welcome-icon">${icon('first')}</span><span class="v32-welcome-copy"><small>FIRST VISIT</small><strong>初めての方</strong><em>受付 → 会計 → 入場まで</em></span><span class="v32-welcome-chev">›</span></button>`}
function playIcon(kind){const map={game:'<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M7 9h10l2 3v6H5v-6l2-3Z" stroke="currentColor" stroke-width="2"/><path d="M8 14h3M9.5 12.5v3M15.5 13.5h.01M17.5 15.5h.01" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>',omikuji:'<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M6 20h12M8 20V9h8v11M7 9h10l-1-4H8L7 9Z" stroke="currentColor" stroke-width="2"/><path d="M12 5V3" stroke="currentColor" stroke-width="2"/></svg>',stamp:'<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M6 18h12M8 18v-4h8v4M9 14l1-7h4l1 7M9 7h6" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>'};return map[kind]||''}
function playMarkup(){return `<section class="v32-play"><div class="v32-section-head"><small>FUN</small><h2>お楽しみ</h2></div><div class="v7-play-row"><button class="v7-play-item" type="button" data-v7-view="game" ${feature('game')?'':'disabled'}><span class="v7-play-icon">${playIcon('game')}</span>ミニゲーム${feature('game')?'':'<small>準備中</small>'}</button><button class="v7-play-item" type="button" data-v7-view="omikuji" ${feature('omikuji')?'':'disabled'}><span class="v7-play-icon">${playIcon('omikuji')}</span>おみくじ${feature('omikuji')?'':'<small>準備中</small>'}</button><button class="v7-play-item" type="button" data-v7-view="stamp" ${feature('stamp')?'':'disabled'}><span class="v7-play-icon">${playIcon('stamp')}</span>スタンプ${feature('stamp')?'':'<small>準備中</small>'}</button></div></section>`}
function guideSection(){return guideMarkup()}
function baseHome(){return `<section class="home-shell v7-home v32-home"><div id="v7Hero" class="v32-hero v32-neutral"><div class="v32-state-label">確認中</div><h1>受付状況を確認しています</h1><p>最新の受付状況を確認しています。</p></div><button id="v7Today" class="v7-today v32-today" type="button" data-v7-view="timeguide" aria-label="本日の営業・利用時間を確認"><span class="v32-today-cell"><small>本日の営業</small><strong>確認中</strong></span><span class="v32-today-cell"><small>利用時間</small><strong>—</strong></span><span class="v32-today-cell"><small>閉館</small><strong>—</strong></span><span class="v32-today-chev">›</span></button>${welcomeMarkup()}${guideSection()}${playMarkup()}</section>`}
function heroMarkup(data={}){const kind=String(data.kind||'sync');if(kind==='waiting'){const n=Number(data.ahead);if(!Number.isFinite(n))return heroMarkup({kind:'sync',receipt:data.receipt,message:'最新の順番を確認しています。'});return{kind,html:`<div class="v32-state-top"><span class="v32-dot"></span><strong>呼出待ち</strong></div><div class="v32-wait-grid"><div class="v32-ahead"><small>あなたの前</small><div><strong>${n}</strong><span>組</span></div></div><div class="v32-eta"><small>待ち時間の目安</small><strong>${etaText(n)}</strong></div></div><p>順番になるとLINEでお知らせします。</p><button class="v32-action dark" type="button" data-v7-view="callstatus">呼出状況を見る <span>›</span></button>`}}
if(kind==='calling')return{kind,html:`<div class="v32-state-label">ただいま呼出中</div><h1>入場できます！</h1><p><strong>呼出後30分以内</strong>にASOBooN入口へお越しください。</p><button class="v32-action green" type="button" data-v7-view="callstatus">受付番号・詳細を見る <span>›</span></button>`};
if(kind==='guide')return{kind,html:`<div class="v32-state-label">ご案内中</div><h1>スタッフのご案内をご確認ください</h1><p>一時退場・再入場のルールはこちらから確認できます。</p><button class="v32-action dark" type="button" data-v7-view="entry">一時退場・再入場を見る <span>›</span></button>`};
if(kind==='none'&&data.canceled){const a=availability();return{kind:'canceled',html:`<div class="v32-state-label">取消済み</div><h1>受付は取消になっています</h1><p>${a.type==='open'?'新しく順番を取る場合は、当日受付からお進みください。':a.message}</p>${a.type==='open'?'<button class="v32-action dark" type="button" data-v7-view="reception">当日受付をする <span>›</span></button>':''}`}}
if(kind==='none'){const a=availability();if(a.type!=='open')return{kind:a.type,html:`<div class="v32-state-label">${esc(a.tag)}</div><h1>${esc(a.title)}</h1><p>${esc(a.message)}</p><button class="v32-action dark" type="button" data-v7-view="first">利用案内を見る <span>›</span></button>`};return{kind,html:`<div class="v32-state-label">本日のご利用</div><h1>本日の当日受付</h1><p>利用する回と人数を選んで、LINEで順番を取ります。</p><button class="v32-action orange" type="button" data-v7-view="reception">当日受付をする <span>›</span></button>`}}
return{kind:'sync',html:`<div class="v32-state-label">確認中</div><h1>受付状況を確認しています</h1><p>${esc(data.message||'最新の受付状況を確認しています。')}</p>${data.receipt?'<button class="v32-action dark" type="button" data-v7-view="callstatus">呼出状況を確認する <span>›</span></button>':''}`}}
function renderHero(data={}){const hero=root.querySelector('#v7Hero');if(!hero)return;const view=heroMarkup(data);const a=availability();const sig=JSON.stringify([view.kind,data.receipt,data.ahead,data.canceled,data.message,a.type,day?.operationalDate,day?.closingTime]);if(sig===lastSignature&&hero.dataset.v32Rendered==='1')return;lastSignature=sig;hero.dataset.v32Rendered='1';hero.className=`v32-hero v32-${view.kind}`;hero.innerHTML=view.html}
function patchToday(){const box=root.querySelector('#v7Today');if(!box)return;const labels=box.querySelectorAll('small'),vals=box.querySelectorAll('strong');if(day){const now=nowJst();setText(labels[0],String(day.operationalDate||'')===now.date?'本日の営業':'次の営業日');setText(vals[0],day.isClosed?'休館':day.businessType||'—');setText(vals[1],day.isClosed?'—':day.durationLabel||'—');setText(vals[2],day.isClosed?'—':day.closingTime||'—');box.classList.toggle('closed',Boolean(day.isClosed));return}setText(vals[0],dayError?'確認できません':'確認中');setText(vals[1],'—');setText(vals[2],'—')}
function patchHome({rebuild=false}={}){if(currentView()!=='home'){document.body.classList.remove('v32-home-active');return}const existing=root.querySelector('.v32-home');if(existing&&!rebuild){if(!latestStatus&&window.ASOBOON_HOME_STATUS_SNAPSHOT)latestStatus=window.ASOBOON_HOME_STATUS_SNAPSHOT;patchToday();renderHero(latestStatus||{kind:'sync'});return}const old=existing||root.querySelector('.home-shell');if(!old)return;lastSignature='';document.body.classList.add('v32-home-active');const brandSmall=document.querySelector('.brand small');if(brandSmall)brandSmall.textContent='川口ハイウェイオアシス';old.outerHTML=baseHome();patchToday();if(!latestStatus&&window.ASOBOON_HOME_STATUS_SNAPSHOT)latestStatus=window.ASOBOON_HOME_STATUS_SNAPSHOT;renderHero(latestStatus||{kind:'sync'})}
async function refreshDay(force=false){if(dayLoading||typeof D.getCurrent!=='function')return;dayLoading=true;dayError='';try{day=await D.getCurrent({force});if(!day?.ok)throw Error('BUSINESS_DAY_UNAVAILABLE')}catch(e){day=null;dayError=String(e?.message||e||'BUSINESS_DAY_UNAVAILABLE')}finally{dayLoading=false;if(currentView()==='home'){lastSignature='';patchToday();renderHero(latestStatus||{kind:'none'})}}}
window.addEventListener('asoboon:v8-home-status',e=>{latestStatus=e.detail||{kind:'sync'};if(currentView()==='home'){lastSignature='';patchHome()}});
window.addEventListener('popstate',()=>setTimeout(()=>{lastSignature='';if(window.ASOBOON_HOME_STATUS_SNAPSHOT)latestStatus=window.ASOBOON_HOME_STATUS_SNAPSHOT;patchHome()},0));
window.addEventListener('focus',()=>{if(currentView()==='home')void refreshDay(true)});
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&currentView()==='home')void refreshDay(true)});
patchHome();void refreshDay(false);
})();