(()=>{'use strict';
const E=window.ASOBOON_V2_ENV||{},F=E.featureFlags||{},D=window.ASOBOON_V2_BUSINESS_DAY||{},root=document.getElementById('app');if(!root)return;
const COPY={ja:{loading:'読み込み中',today:'本日の営業',hours:'利用時間',close:'閉館',guide:'ASOBooNガイド',fun:'お楽しみ',first:'初めての方',firstSub:'受付から入場まで',price:'料金',priceSub:'大人600円・子ども900円',parking:'駐車場・アクセス',parkingSub:'一般道・高速道路からの行き方',rules:'館内ルール',rulesSub:'遊ぶ前に確認',entry:'一時退場・再入場',entrySub:'外出するときはこちら',game:'ミニゲーム',fortune:'おみくじ',stamp:'スタンプ',soon:'準備中'}};
const T=COPY.ja,icons={ticket:'<path d="M5 7.5A2.5 2.5 0 0 0 7.5 5h9A2.5 2.5 0 0 0 19 7.5v1a2.5 2.5 0 0 0 0 5v1A2.5 2.5 0 0 0 16.5 17h-9A2.5 2.5 0 0 0 5 14.5v-1a2.5 2.5 0 0 0 0-5z"/><path d="M12 7v10"/>',queue:'<circle cx="8" cy="8" r="2.5"/><circle cx="16" cy="8" r="2.5"/><path d="M3.5 18c.5-3.5 2-5 4.5-5s4 1.5 4.5 5M12 14c1-.8 2-1 3.3-1 2.7 0 4.3 1.6 4.7 5"/>',bell:'<path d="M6 16h12l-1.5-2v-3a4.5 4.5 0 0 0-9 0v3zM10 19h4"/>',clock:'<circle cx="12" cy="12" r="8"/><path d="M12 7v5l3 2"/>',person:'<circle cx="12" cy="8" r="3"/><path d="M6 20c.4-4 2.4-6 6-6s5.6 2 6 6"/>',yen:'<path d="m7 5 5 7 5-7M8 12h8M8 15h8M12 12v7"/>',parking:'<rect x="4" y="4" width="16" height="16" rx="3"/><path d="M9 17V7h4a3 3 0 0 1 0 6H9"/>',check:'<path d="M7 4h10v16H7zM9 9l1.5 1.5L14 7M9 15h6"/>',door:'<path d="M5 20V4h11v16M9 12h10M16 9l3 3-3 3"/>',game:'<path d="M7 9h10l3 7a2 2 0 0 1-3 2l-2-2H9l-2 2a2 2 0 0 1-3-2zM8 12v3M6.5 13.5h3M16 12h.01M18 14h.01"/>',fortune:'<path d="M7 4h10v16H7zM9 7h6M10 11h4M9 16h6"/>',stamp:'<path d="M8 12h8l2 5H6zM9 20h6M9 12l1-7h4l1 7"/>',alert:'<path d="M12 4 3.5 19h17zM12 9v4M12 16h.01"/>',arrow:'<path d="m9 6 6 6-6 6"/>'};
const svg=k=>`<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round">${icons[k]||icons.check}</svg>`;
let latest=window.ASOBOON_HOME_STATUS_SNAPSHOT||null,day=null,dayError='',dayLoading=false,lastHero='';
const params=()=>new URLSearchParams(location.search),currentView=()=>String(params().get('view')||'home'),feature=n=>F[n]===true,esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])),setText=(el,text)=>{if(el&&el.textContent!==text)el.textContent=text};
function nowJst(){const p=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date()).map(x=>[x.type,x.value]));return{date:`${p.year}-${p.month}-${p.day}`,minutes:Number(p.hour)*60+Number(p.minute)}}
function clockMinutes(v){const m=String(v||'').match(/^(\d{1,2}):(\d{2})$/);return m?Number(m[1])*60+Number(m[2]):NaN}
function availability(){if(dayError)return{type:'error',title:'営業情報を取得できません',message:'受付画面からお進みください。'};if(!day)return{type:'loading',title:T.loading,message:'営業情報を取得しています。'};const now=nowJst();if(String(day.operationalDate||'')!==now.date)return{type:'ended',title:'本日の営業は終了しました',message:'次の営業日にお待ちしています。'};if(day.isClosed)return{type:'closed',title:'本日は休館日です',message:'次の営業日にお待ちしています。'};const close=clockMinutes(day.closingTime);if(Number.isFinite(close)&&now.minutes>=close)return{type:'ended',title:'本日の営業は終了しました',message:'次の営業日にお待ちしています。'};if(String(day.businessType||'')==='平日')return{type:'onsite',title:'本日は現地受付です',message:'ASOBooN入口へお越しください。'};if(now.minutes<420)return{type:'before',title:'LINE当日受付は7:00から',message:'開始までお待ちください。'};return{type:'open'}}
function round5(x){return Math.max(5,Math.round(x/5)*5)}function eta(n){if(n<=5)return'まもなく';const c=Math.max(1,n*.30);if(c<=4)return'約5分以内';let lo=round5(c*.83),hi=round5(c*1.17);if(hi<=lo)hi=lo+5;return`約${lo}〜${hi}分`}
function action(view,label,tone='neutral'){return `<button class="v38-action ${tone}" type="button" data-v7-view="${view}"><span>${label}</span>${svg('arrow')}</button>`}
function guide(kind,title,sub,view,panel=''){return `<button class="v38-guide-card ${kind}" type="button" data-v7-view="${view}"${panel?` data-v7-panel="${panel}"`:''}><span class="v38-icon">${svg(kind)}</span><span><strong>${title}</strong><small>${sub}</small></span>${svg('arrow')}</button>`}
function fun(kind,title,view){const enabled=feature(view);return `<button class="v38-fun-card ${kind}" type="button" data-v7-view="${view}" ${enabled?'':'disabled'}><span class="v38-fun-icon">${svg(kind)}</span><strong>${title}</strong><small>${enabled?'開く':T.soon}</small></button>`}
function baseHome(){return `<section class="home-shell v38-home" aria-label="ASOBooN HOME"><section id="v38Hero" class="v38-hero loading"><div class="v38-hero-icon">${svg('clock')}</div><div><h1>${T.loading}</h1><p>少しお待ちください。</p></div></section><button id="v38Today" class="v38-today" type="button" data-v7-view="timeguide" aria-label="本日の営業と利用時間"><span>${svg('clock')}<small>${T.today}</small><strong>${T.loading}</strong></span><span><small>${T.hours}</small><strong>—</strong></span><span><small>${T.close}</small><strong>—</strong></span>${svg('arrow')}</button><section class="v38-guide"><h2>${T.guide}</h2><div class="v38-guide-grid">${guide('person',T.first,T.firstSub,'first')}${guide('yen',T.price,T.priceSub,'first','price')}${guide('parking',T.parking,T.parkingSub,'parking')}${guide('check',T.rules,T.rulesSub,'rules')}</div>${guide('door',T.entry,T.entrySub,'entry')}</section><section class="v38-fun"><h2>${T.fun}</h2><div>${fun('game',T.game,'game')}${fun('fortune',T.fortune,'omikuji')}${fun('stamp',T.stamp,'stamp')}</div></section></section>`}
function heroMarkup(data={}){const kind=String(data.kind||'sync'),receipt=String(data.receipt||'').trim();if(kind==='waiting'){const n=Number(data.ahead);if(!Number.isFinite(n))return heroMarkup({kind:'sync',receipt});const proximity=n<=3?'ready':n<=5?'near':n<=10?'closer':n>=20?'far':'steady';return{kind:`waiting ${proximity}`,html:`<div class="v38-hero-icon">${svg('queue')}</div><div class="v38-hero-body"><h1>順番待ち</h1><div class="v38-ahead"><small>あと</small><strong>${n}</strong><span>組</span></div><div class="v38-eta">${eta(n)}</div><p>LINEでお知らせします。</p>${receipt?`<small class="v38-receipt">受付番号 ${esc(receipt)}</small>`:''}${action('callstatus','詳しく見る')}</div>`}}if(kind==='calling')return{kind:'calling',html:`<div class="v38-hero-icon">${svg('bell')}</div><div class="v38-hero-body"><h1>入場できます！</h1><div class="v38-deadline">呼出後30分以内</div>${receipt?`<div class="v38-number"><small>受付番号</small><strong>${esc(receipt)}</strong></div>`:''}${action('callstatus','受付番号を見る','calling')}</div>`};if(kind==='guide')return{kind:'guide',html:`<div class="v38-hero-icon">${svg('clock')}</div><div class="v38-hero-body"><h1>ご利用中</h1><p>必要な案内を選べます。</p><div class="v38-inline-actions">${action('timeguide','何時まで遊べる')}${action('entry','一時退場・再入場')}</div></div>`};if(kind==='none'&&data.canceled){const a=availability();return{kind:'canceled',html:`<div class="v38-hero-icon">${svg('alert')}</div><div class="v38-hero-body"><h1>受付は取消済みです</h1><p>${a.type==='open'?'もう一度申し込めます。':esc(a.message)}</p>${a.type==='open'?action('reception','順番を取る','primary'):''}</div>`}}if(kind==='none'){const a=availability();if(a.type==='open')return{kind:'open',html:`<div class="v38-hero-icon">${svg('ticket')}</div><div class="v38-hero-body"><h1>当日受付</h1><p>利用する回と人数を選びます。</p>${action('reception','順番を取る','primary')}</div>`};return{kind:a.type,html:`<div class="v38-hero-icon">${svg(a.type==='error'?'alert':'clock')}</div><div class="v38-hero-body"><h1>${esc(a.title)}</h1><p>${esc(a.message)}</p>${action('first','利用案内へ')}</div>`}}return{kind:'sync',html:`<div class="v38-hero-icon">${svg('clock')}</div><div class="v38-hero-body"><h1>${T.loading}</h1><p>${esc(data.message||'少しお待ちください。')}</p>${receipt?action('callstatus','詳しく見る'):''}</div>`}}
function renderHero(data={}){const el=root.querySelector('#v38Hero');if(!el)return;const v=heroMarkup(data),sig=JSON.stringify([v.kind,data.receipt,data.ahead,data.canceled,data.message,day?.operationalDate,day?.closingTime,dayError]);if(sig===lastHero&&el.dataset.rendered==='1')return;lastHero=sig;el.dataset.rendered='1';el.className=`v38-hero ${v.kind}`;el.innerHTML=v.html}
function patchToday(){const box=root.querySelector('#v38Today');if(!box)return;const labels=box.querySelectorAll('small'),vals=box.querySelectorAll('strong');if(day){setText(vals[0],day.isClosed?'休館':day.businessType||'—');setText(vals[1],day.isClosed?'—':day.durationLabel||'—');setText(vals[2],day.isClosed?'—':day.closingTime||'—');box.classList.toggle('closed',Boolean(day.isClosed));return}setText(vals[0],dayError?'取得できません':T.loading);setText(vals[1],'—');setText(vals[2],'—')}
function mount(){if(currentView()!=='home'){document.body.classList.remove('v38-home-active');return}if(!root.querySelector('.v38-home')){const old=root.querySelector('.home-shell');if(!old)return;old.outerHTML=baseHome()}document.body.classList.remove('v35-home-active','v37-home-active');document.body.classList.add('v38-home-active');const brand=document.querySelector('.brand small');setText(brand,'川口ハイウェイオアシス');patchToday();if(!latest&&window.ASOBOON_HOME_STATUS_SNAPSHOT)latest=window.ASOBOON_HOME_STATUS_SNAPSHOT;renderHero(latest||{kind:'sync'})}
async function refreshDay(force=false){if(dayLoading||typeof D.getCurrent!=='function')return;dayLoading=true;dayError='';try{day=await Promise.race([D.getCurrent({force}),new Promise((_,reject)=>setTimeout(()=>reject(Error('BUSINESS_DAY_HOME_TIMEOUT')),4500))]);if(!day?.ok)throw Error('BUSINESS_DAY_UNAVAILABLE')}catch(e){day=null;dayError=String(e?.message||e||'BUSINESS_DAY_UNAVAILABLE')}finally{dayLoading=false;if(currentView()==='home'){lastHero='';patchToday();renderHero(latest||{kind:'none'})}}}
window.addEventListener('asoboon:v8-home-status',e=>{latest=e.detail||{kind:'sync'};if(currentView()==='home'){lastHero='';mount()}});window.addEventListener('asoboon:v2-route-rendered',()=>{lastHero='';mount()});window.addEventListener('focus',()=>{if(currentView()==='home')void refreshDay(true)});document.addEventListener('visibilitychange',()=>{if(!document.hidden&&currentView()==='home')void refreshDay(true)});mount();void refreshDay(false);
})();
