(()=>{'use strict';
const E=window.ASOBOON_V2_ENV||{};
const F=E.featureFlags||{};
const D=window.ASOBOON_V2_BUSINESS_DAY||{};
const root=document.getElementById('app');
if(!root)return;
let rootObserver=null,statusObserver=null,statusProbe=null,lastSignature='';
const FIRST_KEY='asoboon_v2_home_v7_seen';
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function currentView(){return String(new URLSearchParams(location.search).get('view')||'home')}
function route(view,panel=''){if(typeof window.ASOBOON_V7_NAVIGATE==='function'){window.ASOBOON_V7_NAVIGATE(view,panel);return}const u=new URL(E.endpoint||location.href,location.href);u.search='';u.hash='';u.searchParams.set('view',view);u.searchParams.set('mode','before');if(panel)u.searchParams.set('panel',panel);location.href=u.href}
function feature(name){return F[name]===true}
function proximity(n){if(n<=3)return'arrival';if(n<=10)return'near';if(n<=20)return'mid';return'far'}
function queueMessage(n){if(n<=2)return'もうすぐご案内です！';if(n<=5)return'そろそろ準備しよう！';if(n<=10)return'だんだん近づいてきました！';if(n<=20)return'少しずつ順番が近づいています';return'まだ少し時間があります'}
function carPosition(n){if(n<=0)return 76;if(n>=20)return 7;return Math.round(7+(20-n)/20*69)}
function carSvg(){return `<svg viewBox="0 0 74 42" fill="none" aria-hidden="true"><defs><radialGradient id="v7hl" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="translate(8 25) rotate(180) scale(20 11)"><stop stop-color="#FFF3C8" stop-opacity=".95"/><stop offset="1" stop-color="#FFF3C8" stop-opacity="0"/></radialGradient></defs><path class="v7-headlight" d="M11 20 0 16v18l12-5Z" fill="url(#v7hl)"/><path d="M14 29h5l5-13c1-3 4-5 7-5h15c3 0 6 1 8 4l6 9h4c3 0 4 2 4 5v3H14v-3Z" fill="#F8F8F6"/><path d="M28 14h18c2 0 4 1 5 3l4 6H22l4-7c.4-1 1-2 2-2Z" fill="#BFD6E2"/><circle cx="25" cy="31" r="5" fill="#1E252A"/><circle cx="56" cy="31" r="5" fill="#1E252A"/><circle cx="25" cy="31" r="2" fill="#B9C7CE"/><circle cx="56" cy="31" r="2" fill="#B9C7CE"/></svg>`}
function flagSvg(){return '<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M7 20V4M8 5h9l-2 3 2 3H8" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"/></svg>'}
function highway(ahead){return `<div class="v7-highway" aria-hidden="true"><div class="v7-sign"><strong>ASOBooN</strong><small>出口 ←</small></div><div class="v7-road"><span class="v7-goal-glow"></span><span class="v7-goal">${flagSvg()}</span><span class="v7-car" style="--car-pos:${carPosition(ahead)}%">${carSvg()}</span></div></div>`}
function icon(kind){const map={first:'<svg viewBox="0 0 24 24" fill="none"><circle cx="12" cy="8" r="3" stroke="currentColor" stroke-width="2"/><path d="M6 20c.4-4 2.4-6 6-6s5.6 2 6 6" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>',price:'<svg viewBox="0 0 24 24" fill="none"><path d="M5 5h14v14H5z" stroke="currentColor" stroke-width="2"/><path d="M8 9h8M8 13h8M8 17h5" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>',entry:'<svg viewBox="0 0 24 24" fill="none"><path d="M5 20V4h11v16M9 12h10M16 9l3 3-3 3" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>',rules:'<svg viewBox="0 0 24 24" fill="none"><path d="M7 4h10v16H7z" stroke="currentColor" stroke-width="2"/><path d="m9 9 1.5 1.5L14 7M9 15h6" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>'};return map[kind]||''}
function guideRow(kind,label,sub,view,relevant=false,panel=''){return `<button class="v7-guide-row${relevant?' relevant':''}" type="button" data-v7-view="${view}"${panel?` data-v7-panel="${panel}"`:''}><span class="v7-guide-icon">${icon(kind)}</span><span class="v7-guide-copy"><strong>${label}${relevant?'<span class="v7-chip">いま使う</span>':''}</strong><small>${sub}</small></span><span class="v7-chev">›</span></button>`}
function baseHome(){return `<section class="home-shell v7-home"><div id="v7Hero" class="v7-hero light"><div class="v7-simple"><span class="v7-tag">確認中</span><h1>受付状況を確認しています</h1><p>最新の受付状況を安全に確認しています。</p></div></div><section id="v7Today" class="v7-today" aria-label="本日の営業"><div><small>本日の営業</small><strong>確認中</strong></div><div><small>利用時間</small><strong>—</strong></div><div><small>閉館</small><strong>—</strong></div></section><section class="v7-section"><h2 class="v7-section-title">ご案内</h2><div id="v7Guide" class="v7-guide">${guideRow('first','初めての方','利用の流れ','first')}${guideRow('price','料金','料金・支払い','first',false,'price')}${guideRow('entry','入場・退場','受付から退場まで','entry')}${guideRow('rules','館内ルール','安全のための案内','rules')}</div><button class="v7-more" type="button" data-v7-view="parking" data-v7-panel="info"><span>その他のご案内</span><span>›</span></button></section><section class="v7-play"><h2 class="v7-section-title">ASOBooNで遊ぶ</h2><div class="v7-play-row"><button class="v7-play-item" type="button" data-v7-view="game" ${feature('game')?'':'disabled'}><span class="v7-play-icon">▣</span>ミニゲーム${feature('game')?'':'<small>準備中</small>'}</button><button class="v7-play-item" type="button" data-v7-view="omikuji" ${feature('omikuji')?'':'disabled'}><span class="v7-play-icon">◇</span>おみくじ${feature('omikuji')?'':'<small>準備中</small>'}</button><button class="v7-play-item" type="button" data-v7-view="stamp" ${feature('stamp')?'':'disabled'}><span class="v7-play-icon">◎</span>スタンプ${feature('stamp')?'':'<small>準備中</small>'}</button></div></section></section>`}
function setRelevant(kind){document.querySelectorAll('.v7-guide-row').forEach(el=>{const v=el.dataset.v7View;const rel=kind==='entry'?v==='entry':kind==='rules'?v==='rules':false;el.classList.toggle('relevant',rel);const s=el.querySelector('.v7-chip');if(rel&&!s){el.querySelector('strong')?.insertAdjacentHTML('beforeend','<span class="v7-chip">いま使う</span>')}if(!rel&&s)s.remove()})}
function firstUseNote(){try{const seen=localStorage.getItem(FIRST_KEY)==='1';if(!seen)localStorage.setItem(FIRST_KEY,'1');return!seen}catch{return false}}
function renderHero(kind,data={}){const hero=document.getElementById('v7Hero');if(!hero)return;const sig=JSON.stringify([kind,data.receipt,data.ahead,data.title]);if(sig===lastSignature)return;lastSignature=sig;setRelevant(kind==='guide'?'entry':null);
 if(kind==='waiting'){const n=Number.isFinite(Number(data.ahead))?Math.max(0,Number(data.ahead)):null;if(n==null){renderHero('sync',data);return}const first=firstUseNote();hero.className=`v7-hero prox-${proximity(n)}`;hero.innerHTML=`<div class="v7-hero-inner"><span class="v7-tag">呼出待ち</span><div class="v7-center"><div class="v7-label">あなたの前</div><div class="v7-count"><span class="v7-num">${n}</span><span class="v7-unit">組</span></div><div class="v7-message">${queueMessage(n)}</div>${first?'<div class="v7-note">順番になるとLINEでお知らせします。</div>':''}</div>${highway(n)}<div class="v7-ticket"><span>受付番号</span><strong>${esc(data.receipt||'—')}</strong></div><button class="v7-primary" type="button" data-v7-view="callstatus">呼出状況を見る</button><button class="v7-secondary" type="button" data-v7-view="callstatus" data-v7-panel="detail">受付詳細 ›</button></div>`}
 else if(kind==='calling'){hero.className='v7-hero prox-arrival';hero.innerHTML=`<div class="v7-hero-inner"><span class="v7-tag">ただいま呼出中</span><div class="v7-call-title"><h1>入場できます！</h1><p>ASOBooN入口へお越しください。</p></div>${highway(0)}<div class="v7-ticket"><span>受付番号</span><strong>${esc(data.receipt||'—')}</strong></div><button class="v7-primary" type="button" data-v7-view="callstatus">受付番号を表示する</button></div>`;setRelevant('entry')}
 else if(kind==='guide'){hero.className='v7-hero light';hero.innerHTML=`<div class="v7-simple"><span class="v7-tag">ご案内中</span><h1>スタッフのご案内に<br>お進みください</h1><p>受付でスタッフのご案内をご確認ください。</p><button class="v7-primary" type="button" data-v7-view="entry">入場・退場の案内を見る</button><button class="v7-secondary" type="button" data-v7-view="callstatus">受付状況を見る</button></div>`;setRelevant('entry')}
 else if(kind==='none'){hero.className='v7-hero light';hero.innerHTML=`<div class="v7-simple"><span class="v7-tag">受付前</span><h1>受付</h1><p>${data.canceled?'この受付は取消になっています。新しく受付する場合はこちらから。':'ASOBooNをご利用の方はこちらから受付してください。'}</p><button class="v7-primary" type="button" data-v7-view="reception">受付する</button></div>`;setRelevant(null)}
 else{hero.className='v7-hero light';hero.innerHTML=`<div class="v7-simple"><span class="v7-tag">確認中</span><h1>受付状況を確認しています</h1><p>${esc(data.message||'最新情報を取得しています。古い順番は現在値として表示しません。')}</p><button class="v7-primary" type="button" data-v7-view="callstatus">呼出状況を確認する</button></div>`;setRelevant(null)}
 bindV7Buttons(hero)}
function bindV7Buttons(scope=document){scope.querySelectorAll('[data-v7-view]').forEach(el=>{if(el.dataset.v7Bound==='1'||el.disabled)return;el.dataset.v7Bound='1';el.addEventListener('click',()=>route(el.dataset.v7View,el.dataset.v7Panel||''))})}
function statusFromProbe(){if(!statusProbe)return;const box=statusProbe.querySelector('#csState');const title=String(statusProbe.querySelector('#csTitle')?.textContent||'');const receipt=String(statusProbe.querySelector('#csReceipt')?.textContent||'').replace(/[^0-9A-Za-z-]/g,'')||'—';const aheadText=String(statusProbe.querySelector('#csAhead')?.textContent||'');const ahead=/^\d+$/.test(aheadText.trim())?Number(aheadText.trim()):null;const classes=box?.classList;if(classes?.contains('waiting'))return renderHero('waiting',{ahead,receipt,title});if(classes?.contains('calling'))return renderHero('calling',{receipt,title});if(classes?.contains('hold')||classes?.contains('processing')||classes?.contains('done'))return renderHero('guide',{receipt,title});if(classes?.contains('canceled'))return renderHero('none',{receipt,title,canceled:true});if(/本日の受付が見つかりません/.test(title))return renderHero('none',{receipt,title});const err=String(statusProbe.querySelector('#csError')?.textContent||'');return renderHero('sync',{receipt,title,message:err||'最新情報を取得しています。古い順番は現在値として表示しません。'})}
function stopProbe(){try{statusObserver?.disconnect()}catch{}statusObserver=null;try{window.ASOBOON_V2_CALLSTATUS?.unmount?.()}catch{}statusProbe?.remove();statusProbe=null;lastSignature=''}
function startProbe(){if(statusProbe)return;const mod=window.ASOBOON_V2_CALLSTATUS;if(!mod?.render||!mod?.mount){renderHero('sync',{message:'呼出状況モジュールを確認しています。'});return}statusProbe=document.createElement('div');statusProbe.id='v7StatusProbe';statusProbe.setAttribute('aria-hidden','true');statusProbe.innerHTML=mod.render();document.body.appendChild(statusProbe);statusObserver=new MutationObserver(statusFromProbe);statusObserver.observe(statusProbe,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['class','hidden']});mod.mount();setTimeout(statusFromProbe,0);setTimeout(statusFromProbe,500)}
async function loadToday(){const box=document.getElementById('v7Today');if(!box||typeof D.getCurrent!=='function')return;try{const day=await D.getCurrent();if(!document.getElementById('v7Today'))return;const vals=box.querySelectorAll('strong');if(vals[0])vals[0].textContent=day.isClosed?'休館':day.businessType;if(vals[1])vals[1].textContent=day.isClosed?'—':day.durationLabel;if(vals[2])vals[2].textContent=day.isClosed?'—':day.closingTime||'—';box.classList.toggle('closed',Boolean(day.isClosed))}catch{const vals=box.querySelectorAll('strong');if(vals[0])vals[0].textContent='確認できません';if(vals[1])vals[1].textContent='—';if(vals[2])vals[2].textContent='—'}}
function patchHome(){if(currentView()!=='home'){document.body.classList.remove('v7-home-active');stopProbe();return}const old=root.querySelector('.home-shell:not(.v7-home)');if(!old)return;if(root.querySelector('.v7-home'))return;stopProbe();document.body.classList.add('v7-home-active');const brandSmall=document.querySelector('.brand small');if(brandSmall)brandSmall.textContent='川口ハイウェイオアシス';old.outerHTML=baseHome();bindV7Buttons(document);startProbe();void loadToday()}
function watch(){rootObserver=new MutationObserver(()=>queueMicrotask(patchHome));rootObserver.observe(root,{childList:true,subtree:true});patchHome();setTimeout(patchHome,50);setTimeout(patchHome,300)}
watch();
})();
