(()=>{'use strict';
const C=window.QUEUE_PRODUCT_CONFIG||{},API=window.QueueProductAPI,$=id=>document.getElementById(id),STORAGE='queue_product_current_reservation_v1';
const S={slots:[],slot:null,waitInfo:null,adults:1,paidChildren:0,infants:0,agree:false,submitting:false,operationalDay:'',dayMode:'today',closed:false,server:{maxTotalPeople:Number(C.maxTotalPeople||10),childrenPerAdult:Number(C.childrenPerAdult||3)}};
const money=n=>`${Number(n||0).toLocaleString('ja-JP')}円`,brand=String(C.brandName||'施設');document.querySelectorAll('[data-brand]').forEach(x=>x.textContent=brand);document.title=`${brand}｜受付`;
function dateJa(ymd){const[,m,d]=String(ymd).split('-');return `${Number(m)}月${Number(d)}日`}function ymdAdd(base,n){const[y,m,d]=base.split('-').map(Number),x=new Date(Date.UTC(y,m-1,d+n,12));return `${x.getUTCFullYear()}-${String(x.getUTCMonth()+1).padStart(2,'0')}-${String(x.getUTCDate()).padStart(2,'0')}`}
function resolveDay(){const p=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:C.timezone||'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',hourCycle:'h23'}).formatToParts(new Date()).map(x=>[x.type,x.value])),base=`${p.year}-${p.month}-${p.day}`,h=Number(p.hour),close=Number(C.receptionCloseHour??18),next=Number(C.nextDayOpenHour??19);S.closed=h>=close&&h<next;S.dayMode=h>=next?'tomorrow':'today';S.operationalDay=S.dayMode==='tomorrow'?ymdAdd(base,1):base;$('dayTitle').textContent=`${S.dayMode==='tomorrow'?'明日':'本日'} ${dateJa(S.operationalDay)} の入場受付`;$('daySub').textContent=S.dayMode==='tomorrow'?'翌日の受付を行っています':'受付状況は自動で更新されます';$('heroTitle').textContent=S.dayMode==='tomorrow'?'明日の入場受付':'本日の入場受付';$('closedCard').hidden=!S.closed;$('flow').hidden=S.closed}
function blocked(x){const id=String(x.waitTypeId||''),name=String(x.waitTypeName||'').normalize('NFKC');return (C.blockedWaitTypeIds||[]).map(String).includes(id)||/WEB/i.test(name)||(C.blockedNamePatterns||[]).some(p=>name.includes(String(p)))}function norm(v){return String(v||'').normalize('NFKC').replace(/\s/g,'').toLowerCase()}function info(slot){const details=Array.isArray(S.waitInfo?.waitDetails)?S.waitInfo.waitDetails:[],hits=details.filter(x=>norm(x.detailedWaitType)===norm(slot.waitTypeName));return hits[0]||null}function remaining(slot){const x=info(slot);return x&&x.remainingNum!=null?Number(x.remainingNum):null}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}function renderSlots(){const wrap=$('slotList');wrap.innerHTML='';if(!S.slots.length){wrap.innerHTML='<div class="msg info">現在受付できる回はありません。</div>';return}S.slots.forEach(s=>{const r=remaining(s),b=document.createElement('button');b.className='slot'+(S.slot&&String(S.slot.waitTypeId)===String(s.waitTypeId)?' active':'');b.type='button';b.dataset.id=s.waitTypeId;b.innerHTML=`<strong>${esc(s.waitTypeName||'受付')}</strong><span class="remain ${r==null?'unknown':r<=10?'low':''}">${r==null?'受付状況を確認中':`残り ${Math.max(0,r)}`}</span>`;wrap.appendChild(b)})}
function children(){return S.paidChildren+S.infants}function total(){return S.adults+children()}function validPeople(){return total()<=S.server.maxTotalPeople&&children()<=S.adults*S.server.childrenPerAdult}
function update(){$('adultOut').textContent=S.adults;$('childOut').textContent=S.paidChildren;$('infantOut').textContent=S.infants;$('adultPrice').textContent=`${money(C.priceAdult)} / 1名`;$('childPrice').textContent=`${money(C.priceChild)} / 1名`;$('peopleRule').textContent=`1受付 合計${S.server.maxTotalPeople}名まで / おとな1名につき子ども${S.server.childrenPerAdult}名まで`;$('adultLine').textContent=`${S.adults}名 × ${money(C.priceAdult)} = ${money(S.adults*Number(C.priceAdult||0))}`;$('childLine').textContent=`${S.paidChildren}名 × ${money(C.priceChild)} = ${money(S.paidChildren*Number(C.priceChild||0))}`;$('totalLine').textContent=money(S.adults*Number(C.priceAdult||0)+S.paidChildren*Number(C.priceChild||0));const n=$('capacityNote');n.className='capacity-note'+(validPeople()?'':' bad');n.textContent=validPeople()?`合計 ${total()}名で受付できます。`:`人数条件を確認してください（合計${S.server.maxTotalPeople}名まで）。`;$('reviewBtn').disabled=!(S.slot&&S.agree&&validPeople())||S.submitting}
function change(a){if(a==='adultMinus')S.adults=Math.max(1,S.adults-1);if(a==='adultPlus')S.adults++;if(a==='childMinus')S.paidChildren=Math.max(0,S.paidChildren-1);if(a==='childPlus')S.paidChildren++;if(a==='infantMinus')S.infants=Math.max(0,S.infants-1);if(a==='infantPlus')S.infants++;update()}function summary(){return `<div class="line"><span>受付日</span><strong>${dateJa(S.operationalDay)}</strong></div><div class="line"><span>入場する回</span><strong>${esc(S.slot?.waitTypeName||'')}</strong></div><div class="line"><span>人数</span><strong>${total()}名</strong></div><div class="line total"><span>料金</span><strong>${money(S.adults*Number(C.priceAdult||0)+S.paidChildren*Number(C.priceChild||0))}</strong></div>`}
function persist(r){localStorage.setItem(STORAGE,JSON.stringify(r))}function current(){try{const r=JSON.parse(localStorage.getItem(STORAGE)||'null');return r&&r.receiptNo&&r.operationalDay===S.operationalDay?r:null}catch{return null}}function renderCurrent(){const r=current();if(!r)return false;$('currentCard').hidden=false;$('flow').hidden=true;$('closedCard').hidden=true;$('currentNo').textContent=r.receiptNo;$('currentSub').textContent=`${r.waitTypeName||'受付'} / ${r.totalPeople||''}名で受付済みです。`;return true}
async function load(){resolveDay();if(renderCurrent())return;try{const [pc,wt,wi]=await Promise.all([API.publicConfig(),API.waitTypes(),API.waitInfo().catch(()=>null)]);if(pc?.ok){S.server.maxTotalPeople=Number(pc.maxTotalPeople||S.server.maxTotalPeople);S.server.childrenPerAdult=Number(pc.childrenPerAdult||S.server.childrenPerAdult)}const list=Array.isArray(wt?.waitTypeList)?wt.waitTypeList:[];S.slots=list.filter(x=>x.dispFlg===true||x.dispFlg===1||x.dispFlg==='1'||String(x.dispFlg).toLowerCase()==='true').filter(x=>!blocked(x)).sort((a,b)=>Number(a.dispOrder??999)-Number(b.dispOrder??999));S.waitInfo=wi?.innerDto?.stores?.[0]||null;renderSlots();update()}catch(e){$('slotList').innerHTML=`<div class="msg bad">${esc(e.message||e)}</div>`}}
async function submit(){if(S.submitting||!S.slot||!S.agree||!validPeople())return;S.submitting=true;update();const b=$('modalConfirm');b.disabled=true;b.textContent='受付中…';try{const r=await API.createReservation({waitTypeId:String(S.slot.waitTypeId),waitTypeName:String(S.slot.waitTypeName||''),operationalDay:S.operationalDay,adults:S.adults,paidChildren:S.paidChildren,infants:S.infants,source:'commercial-customer-v1'});const rec={...r,waitTypeId:String(S.slot.waitTypeId),waitTypeName:String(S.slot.waitTypeName||''),adults:S.adults,paidChildren:S.paidChildren,infants:S.infants,totalPeople:total(),operationalDay:S.operationalDay,createdAt:Date.now()};persist(rec);$('confirmModal').hidden=true;$('flow').hidden=true;$('successCard').hidden=false;$('receiptNo').textContent=rec.receiptNo;$('successSummary').innerHTML=summary();window.scrollTo({top:0,behavior:'smooth'})}catch(e){$('confirmModal').hidden=true;$('receptionMsg').hidden=false;$('receptionMsg').className='msg bad';$('receptionMsg').textContent=e.message||String(e)}finally{S.submitting=false;b.disabled=false;b.textContent='受付を確定する';update()}}
$('slotList').addEventListener('click',e=>{const b=e.target.closest('[data-id]');if(!b)return;S.slot=S.slots.find(x=>String(x.waitTypeId)===String(b.dataset.id))||null;renderSlots();$('slotCard').hidden=true;$('peopleCard').hidden=false;$('waiverCard').hidden=false;window.scrollTo({top:0,behavior:'smooth'});update()});document.addEventListener('click',e=>{const b=e.target.closest('[data-act]');if(b)change(b.dataset.act)});$('backSlots').onclick=()=>{$('slotCard').hidden=false;$('peopleCard').hidden=true;$('waiverCard').hidden=true};$('reloadSlots').onclick=load;$('agree').onchange=e=>{S.agree=e.target.checked;update()};$('reviewBtn').onclick=()=>{$('modalSummary').innerHTML=summary();$('confirmModal').hidden=false};$('modalBack').onclick=()=>{$('confirmModal').hidden=true};$('modalConfirm').onclick=submit;$('waiver').textContent=String(C.waiverText||'施設の利用ルール・スタッフの案内に従ってご利用ください。安全のため、保護者の方はお子さまから目を離さないようお願いいたします。');load();setInterval(()=>{if($('slotCard').hidden)return;load()},30000);
})();
