const BUILD = "2026-08-07-bulk-identity-sync-v14";
const STATIC_CACHE = `boonjump-static-${BUILD}`;
const IMAGE_CACHE = `boonjump-images-${BUILD}`;
const PRECACHE = [
  "./",
  "./index.html",
  "./ranking-client.js?v=236-bulk-identity-14",
  "./manifest.webmanifest",
  "./icons/icon-192.png",
  "./icons/icon-512.png",
  "./icons/icon-maskable-192.png",
  "./icons/icon-maskable-512.png",
  "./assets/cars/bike-body.png",
  "./assets/cars/bike-boost.png",
  "./assets/cars/bike-front.png",
  "./assets/cars/bike-rear.png",
  "./assets/cars/bike-shadow.png",
  "./assets/cars/boon-body.png",
  "./assets/cars/boon-boost.png",
  "./assets/cars/boon-front.png",
  "./assets/cars/boon-rear.png",
  "./assets/cars/boon-shadow.png",
  "./assets/cars/buggy-body.png",
  "./assets/cars/buggy-boost.png",
  "./assets/cars/buggy-front.png",
  "./assets/cars/buggy-rear.png",
  "./assets/cars/buggy-shadow.png",
  "./assets/cars/princess-body.png",
  "./assets/cars/princess-boost.png",
  "./assets/cars/princess-front.png",
  "./assets/cars/princess-rear.png",
  "./assets/cars/princess-shadow.png",
  "./assets/cars/secret-body.png",
  "./assets/cars/secret-boost.png",
  "./assets/cars/secret-front.png",
  "./assets/cars/secret-rear.png",
  "./assets/cars/secret-shadow.png",
  "./assets/cars/sport-body.png",
  "./assets/cars/sport-boost.png",
  "./assets/cars/sport-front.png",
  "./assets/cars/sport-rear.png",
  "./assets/cars/sport-shadow.png",
  "./assets/cars/ssr-body.png",
  "./assets/cars/ssr-boost.png",
  "./assets/cars/ssr-front.png",
  "./assets/cars/ssr-rear.png",
  "./assets/cars/ssr-shadow.png",
  "./assets/cars/suv-body.png",
  "./assets/cars/suv-boost.png",
  "./assets/cars/suv-front.png",
  "./assets/cars/suv-rear.png",
  "./assets/cars/suv-shadow.png",
  "./assets/cars/wagon-body.png",
  "./assets/cars/wagon-boost.png",
  "./assets/cars/wagon-front.png",
  "./assets/cars/wagon-rear.png",
  "./assets/cars/wagon-shadow.png",
  "./assets/cars/bike-front-wheel.png",
  "./assets/cars/bike-rear-wheel.png",
  "./assets/cars/boon-front-wheel.png",
  "./assets/cars/boon-rear-wheel.png",
  "./assets/cars/buggy-front-wheel.png",
  "./assets/cars/buggy-rear-wheel.png",
  "./assets/cars/princess-front-wheel.png",
  "./assets/cars/princess-rear-wheel.png",
  "./assets/cars/sport-front-wheel.png",
  "./assets/cars/sport-rear-wheel.png",
  "./assets/cars/ssr-front-wheel.png",
  "./assets/cars/ssr-rear-wheel.png",
  "./assets/cars/suv-front-wheel.png",
  "./assets/cars/suv-rear-wheel.png",
  "./assets/cars/wagon-front-wheel.png",
  "./assets/cars/wagon-rear-wheel.png",
];
self.addEventListener("message",event=>{if(event.data&&event.data.type==="SKIP_WAITING")self.skipWaiting();});
self.addEventListener("install",event=>{event.waitUntil((async()=>{const staticCache=await caches.open(STATIC_CACHE),imageCache=await caches.open(IMAGE_CACHE);await Promise.allSettled(PRECACHE.map(async path=>{const response=await fetch(path);if(!response.ok)throw new Error(`Precache failed: ${path} (${response.status})`);const target=path.includes("/assets/cars/")||path.includes("/icons/")?imageCache:staticCache;await target.put(path,response);}));})());});
self.addEventListener("activate",event=>{event.waitUntil((async()=>{const keep=new Set([STATIC_CACHE,IMAGE_CACHE]),keys=await caches.keys();await Promise.all(keys.filter(key=>key.startsWith("boonjump-")&&!keep.has(key)).map(key=>caches.delete(key)));await self.clients.claim();})());});
const networkFirstDocument=async request=>{const cache=await caches.open(STATIC_CACHE);try{const response=await fetch(request);if(response.ok)await cache.put("./index.html",response.clone());return response;}catch(_){return(await cache.match("./index.html"))||Response.error();}};
const cacheFirstImage=async request=>{const cache=await caches.open(IMAGE_CACHE),cached=await cache.match(request);if(cached)return cached;const response=await fetch(request);if(response.ok)await cache.put(request,response.clone());return response;};
const networkFirstStatic=async request=>{const cache=await caches.open(STATIC_CACHE);try{const response=await fetch(request);if(response.ok)await cache.put(request,response.clone());return response;}catch(_){return(await cache.match(request))||Response.error();}};
self.addEventListener("fetch",event=>{const request=event.request;if(request.method!=="GET")return;const url=new URL(request.url);if(url.origin!==self.location.origin)return;if(request.mode==="navigate"||request.destination==="document"){event.respondWith(networkFirstDocument(request));return;}const isGameImage=request.destination==="image"&&(url.pathname.includes("/assets/cars/")||url.pathname.includes("/icons/"));event.respondWith(isGameImage?cacheFirstImage(request):networkFirstStatic(request));});
