/* Safe sales/demo configuration. Replace this file per facility; never add secrets. */
window.QUEUE_PRODUCT_CONFIG = Object.freeze({
  productVersion: '1.0.0',
  demoMode: true,
  brandName: 'QUEUE PRODUCT DEMO',
  backendUrl: '',
  locale: 'ja-JP',
  timezone: 'Asia/Tokyo',
  staffKeyStorageKey: 'queue_product_staff_key',
  requestTimeoutMs: 10000,
  mutationPollMs: 650,
  mutationMaxPolls: 12,
  receptionCloseHour: 18,
  nextDayOpenHour: 19,
  maxTotalPeople: 10,
  childrenPerAdult: 3,
  priceAdult: 600,
  priceChild: 900,
  waiverText: '施設の利用ルール・スタッフの案内に従ってご利用ください。安全のため、保護者の方はお子さまから目を離さないようお願いいたします。',
  blockedWaitTypeIds: [],
  blockedNamePatterns: ['テスト','ご待機者専用','待機者専用'],
  staffRefreshMs: 10000,
  autoCallingPool: 10,
  autoCallGapMs: 700,
  autoStopTime: '18:00',
  slotStartOverrides: {D101:'00:00',D102:'23:59'}
});
