(()=>{'use strict';
const C=window.QUEUE_PRODUCT_CONFIG||{},API=window.QueueProductAPI,$=id=>document.getElementById(id);
const S={ledger:[],slots:[],groups:new Map(),autoEnabled:false,callEnabled:false,triggerInstalled:false,busy:false,lastError:'',day:'',timer:0,lastSuccessAt:0};
const pool=Number(C.autoCallingPool||10),refreshMs=Number(C.staffRefreshMs||10000);
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const digits=v=>String(v??'').normalize('NFKC').replace(/\D/g,'').replace(/^0+(?=\d)/,'');
function log(m){$('log').textContent=`[${new Date().toLocaleTimeString('ja-JP')}] ${m}\n`+$('log').textContent}
function jst(){return Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date()).map(x=>[x.type,x.value]))}
function minOf(h,m){return Number(h)*60+Number(m)}
function parseStart(slot){const override=C.slotStartOverrides?.[String(slot.waitTypeId)];if(override){const m=String(override).match(/^(\d{1,2}):(\d{2})$/);if(m)return{hour:+m[1],minute:+m[2],text:`${String(+m[1]).padStart(2,'0')}:${m[2]}`}}const s=String(slot.waitTypeName||'').normalize('NFKC');let m=s.match(/(?:^|[^\d])([01]?\d|2[0-3])\s*[:：]\s*([0-5]\d)/);if(m)return{hour:+m[1],minute:+m[2],text:`${String(+m[1]).padStart(2,'0')}:${m[2]}`};m=s.match(/(?:^|[^\d])([01]?\d|2[0-3])\s*時\s*([0-5]?\d)\s*分/);if(m)return{hour:+m[1],minute:+m[2],text:`${String(+m[1]).padStart(2,'0')}:${String(+m[2]).padStart(2,'0')}`};m=s.match(/(?:^|[^\d])([01]?\d|2[0-3])\s*時\s*半/);if(m)return{hour:+m[1],minute:30,text:`${String(+m[1]).padStart(2,'0')}:30`};return null}
function blocked(x){const id=String(x.waitTypeId||''),name=String(x.waitTypeName||'').normalize('NFKC');return (C.blockedWaitTypeIds||[]).map(String).includes(id)||/WEB/i.test(name)||(C.blockedNamePatterns||[]).some(p=>name.toLowerCase().includes(String(p).normalize('NFKC').toLowerCase()))}
function rows(id){return S.groups.get(String(id))||[]}function waiting(rs){return rs.filter(r=>String(r.status)==='0'&&String(r.isCalling)!=='1')}function calling(rs){return rs.filter(r=>String(r.status)!=='1'&&String(r.isCalling)==='1')}
function linked(row){const exact=S.ledger.find(x=>String(x.waitTypeId)===String(row.waitTypeId)&&digits(x.receiptNo)===digits(row.number));if(exact)return exact;const hits=S.ledger.filter(x=>digits(x.receiptNo)===digits(row.number));return hits.length===1?hits[0]:null}
function state(r){if(String(r.status)==='1')return['保留中','hold'];if(String(r.isCalling)==='1')return['呼出中','calling'];if(String(r.status)==='4')return['対応中','serving'];return['待ち中','waiting']}
function runState(slot){const p=jst(),now=minOf(p.hour,p.minute),st=parseStart(slot);if(!st)return{active:false,label:'時刻未判定',start:null};if(!S.callEnabled)return{active:false,label:'呼出API確認待ち',start:st};if(!S.autoEnabled)return{active:false,label:'AUTO OFF',start:st};if(now>=18*60)return{active:false,label:'18:00以降休止',start:st};if(now<minOf(st.hour,st.minute))return{active:false,label:`${st.text} 開始待ち`,start:st};return{active:true,label:'サーバーAUTO稼働',start:st}}
async function loadAll(slot){let start=1,all=[];for(let i=0;i<40;i++){const d=await API.reservations(slot.waitTypeId,{isEnabledStatus:'1',sortStatus:'0',isDesc:'0',start:String(start),limit:'100'}),inner=d?.innerDto||{},part=Array.isArray(inner.reservations)?inner.reservations:[];all.push(...part);const count=Number(inner.count||0);if(!part.length||part.length<100||(count&&all.length>=count))break;start+=part.length}S.groups.set(String(slot.waitTypeId),all)}
function render(){let totalW=0,totalC=0,active=0,next=null;const wrap=$('slots');wrap.innerHTML='';for(const slot of S.slots){const rs=rows(slot.waitTypeId),ws=waiting(rs),cs=calling(rs),run=runState(slot),first=ws[0],rec=first&&linked(first);totalW+=ws.length;totalC+=cs.length;if(run.active)active++;else if(run.start&&run.label.includes('開始待ち')&&!next)next=run.start.text;const sec=document.createElement('section');sec.className='slot';const warn=run.active&&first&&!rec?`<div class="slotwarn">⚠️ 先頭 ${esc(first.number)}番 はID未連携。サーバーAUTOは追い越さず停止します。</div>`:'';sec.innerHTML=`<div class="slothead"><div class="slottop"><div class="slotname">${esc(slot.waitTypeName||'名称なし')}</div><span class="slotstatus ${run.active?'running':'wait'}">${esc(run.label)}</span></div><div class="metrics"><div class="metric"><small>待ち中</small><strong>${ws.length}</strong></div><div class="metric"><small>呼出中</small><strong>${cs.length}/${pool}</strong></div><div class="metric"><small>ID連携</small><strong>${ws.filter(r=>linked(r)).length}</strong></div><div class="metric"><small>保留中</small><strong>${rs.filter(r=>String(r.status)==='1').length}</strong></div></div>${warn}</div><div class="rows"></div>`;const body=sec.querySelector('.rows');if(!rs.length)body.innerHTML='<div class="empty">現在の受付はありません。</div>';else rs.forEach(r=>{const x=linked(r),[lab,cls]=state(r),el=document.createElement('div');el.className='row';el.innerHTML=`<div class="num">${esc(r.number||'--')}番</div><div class="meta">${x?'<span class="linked">ID連携済み</span>':'<span class="unlinked">ID未連携</span>'}${x?.totalPeople?` / ${esc(x.totalPeople)}名`:''}</div><span class="badge ${cls}">${lab}</span>`;body.appendChild(el)});wrap.appendChild(sec)}
$('sumWaiting').textContent=totalW;$('sumCalling').textContent=totalC;$('sumActive').textContent=active;$('sumNext').textContent=next||'--';
const gate=$('callGate');if(!S.callEnabled){gate.hidden=false;gate.className='notice locked';gate.textContent='🔒 AirWAIT呼出API確認待ち。受付監視は正常、AUTOはサーバー側でロック中です。'}else if(!S.triggerInstalled){gate.hidden=false;gate.className='notice';gate.textContent='⚠️ サーバーAUTOトリガー未設定。AUTO ON時に自動作成されます。'}else gate.hidden=true;
const fresh=S.lastSuccessAt&&Date.now()-S.lastSuccessAt<30000;if(S.lastError){$('headline').className='headline stop';$('headline').textContent='安全停止中';$('actionHint').textContent=S.lastError}else if(!S.callEnabled){$('headline').className='headline wait';$('headline').textContent='受付監視中・呼出API回答待ち';$('actionHint').textContent='受付・台帳・ID連携は監視継続。AirWAIT回答後に呼出機能だけ開放します。'}else if(S.autoEnabled){$('headline').className='headline good';$('headline').textContent='サーバーAUTO稼働中';$('actionHint').textContent='iPadが閉じてもAUTOは継続します。受付順を維持して最大10組を管理します。'}else{$('headline').className='headline wait';$('headline').textContent='受付監視中・AUTO停止';$('actionHint').textContent='受付状況は監視中です。必要な時だけAUTOをONにしてください。'}
$('backendTop').textContent=fresh?'OK':'要更新';$('backendTop').className=fresh?'ok':'warn';$('airTop').textContent=fresh?'OK':'要更新';$('airTop').className=fresh?'ok':'warn';$('ledgerTop').textContent=fresh?'OK':'要更新';$('ledgerTop').className=fresh?'ok':'warn';$('autoTop').textContent=S.autoEnabled?'ON':'OFF';$('autoTop').className=S.autoEnabled?'ok':'warn';$('autoState').textContent=S.autoEnabled?'AUTO ON':'AUTO OFF';$('autoDesc').textContent=S.callEnabled?(S.autoEnabled?'サーバー側で1分周期。各回開始後、呼出中を最大10組に維持します。':'サーバーAUTOは停止しています。'):'AirWAIT呼出API確認待ちのためAUTOはロックされています。';$('autoOn').disabled=!API.staffKey()||S.autoEnabled||!S.callEnabled;$('autoOff').disabled=!API.staffKey()||!S.autoEnabled}
async function demoFill(){for(const slot of S.slots){const run=runState(slot);if(!run.active)continue;let count=calling(rows(slot.waitTypeId)).length;for(const row of waiting(rows(slot.waitTypeId))){if(count>=pool)break;const rec=linked(row);if(!rec)break;await API.callReservation(String(rec.reserveId));count++;await loadAll(slot)}}}
async function refresh(){if(S.busy||!API.staffKey())return;S.busy=true;const p=jst();S.day=`${p.year}-${p.month}-${p.day}`;$('dayLabel').textContent=`営業日 ${S.day} / 更新 ${new Date().toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit'})}`;try{const [health,snap,types]=await Promise.all([API.health(),API.staffSnapshot(),API.waitTypes()]);if(!health?.ok||!snap?.ok||!types?.ok)throw new Error('バックエンド状態を取得できません。');S.ledger=Array.isArray(snap.reservations)?snap.reservations:[];S.autoEnabled=snap.autoEnabled===true;S.callEnabled=API.demoMode?true:snap.callEnabled===true;S.triggerInstalled=API.demoMode?true:snap.triggerInstalled===true;S.slots=(Array.isArray(types.waitTypeList)?types.waitTypeList:[]).filter(x=>!blocked(x)).sort((a,b)=>{const x=parseStart(a),y=parseStart(b);return x&&y?minOf(x.hour,x.minute)-minOf(y.hour,y.minute):0});await Promise.all(S.slots.map(loadAll));S.lastError='';S.lastSuccessAt=Date.now();if(API.demoMode&&S.autoEnabled)await demoFill();render()}catch(e){S.lastError=String(e.message||e);log(`更新失敗: ${S.lastError}`);render()}finally{S.busy=false}}
function authUi(){const y=!!API.staffKey();$('authSetup').hidden=y;$('authDone').hidden=!y;$('autoOn').disabled=!y;$('autoOff').disabled=!y}
$('saveKey').onclick=()=>{API.setStaffKey($('keyInput').value);$('keyInput').value='';authUi();refresh()};$('changeKey').onclick=()=>{API.setStaffKey('');authUi();S.ledger=[];S.slots=[];S.groups.clear();render()};$('refresh').onclick=refresh;$('autoOn').onclick=async()=>{try{const r=await API.setAutoEnabled(true);S.autoEnabled=r.enabled===true;S.triggerInstalled=r.triggerInstalled!==false;log('サーバーAUTO ON');await refresh()}catch(e){S.lastError=e.message||String(e);log(`AUTO ON失敗: ${S.lastError}`);render()}};$('autoOff').onclick=async()=>{try{await API.setAutoEnabled(false);S.autoEnabled=false;log('サーバーAUTO OFF');render()}catch(e){S.lastError=e.message||String(e);render()}};window.addEventListener('online',refresh);window.addEventListener('pageshow',refresh);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh()});authUi();render();if(API.staffKey())refresh();S.timer=setInterval(refresh,refreshMs);setInterval(render,5000);
})();
