/**
 * ASOBooN MINI App v2 - Review Gateway
 * Review-only simulation. Verifies Review LIFF identity and NEVER writes AirWAIT.
 */
const CFG=Object.freeze({
  VERSION:'1.0.review-sim',ENVIRONMENT:'official-review',CHANNEL_ID:'2009884613',
  ALLOWED_ORIGIN:'https://asoboon.github.io',DEVELOP_PUBLIC:'https://asoboon-miniapp-v2-develop-gateway.asoboon425.workers.dev/',
  LINE_VERIFY:'https://api.line.me/oauth2/v2.1/verify',LINE_PROFILE:'https://api.line.me/v2/profile',
  SESSION_TTL_MS:2*60*60*1000,REQUEST_TTL_MS:24*60*60*1000
});
const WAIT_TYPES=Object.freeze([
  Object.freeze({waitTypeId:'0029',waitTypeName:'10:00回（審査用）',dispFlg:true,usageDispType:'KeySTORE_RECEPTION_ONLY'}),
  Object.freeze({waitTypeId:'0031',waitTypeName:'12:30回（審査用）',dispFlg:true,usageDispType:'KeySTORE_RECEPTION_ONLY'}),
  Object.freeze({waitTypeId:'0033',waitTypeName:'15:00回（審査用）',dispFlg:true,usageDispType:'KeySTORE_RECEPTION_ONLY'})
]);
const ALLOWED_WAIT=new Set(WAIT_TYPES.map(x=>x.waitTypeId));
export default{async fetch(request,env){if(request.method==='OPTIONS')return preflight(request);try{origin(request);if(!env.DB)throw err('DB_NOT_CONFIGURED',503);await schema(env);const u=new URL(request.url);if(request.method==='GET'){const a=String(u.searchParams.get('action')||'health');if(a==='health')return json(request,health(env));if(a==='waitTypes')return json(request,{ok:true,reviewSimulation:true,waitTypes:WAIT_TYPES,version:CFG.VERSION});if(a==='businessDay')return json(request,reviewBusinessDay(u.searchParams.get('date')));if(a==='crowdRemaining')return await proxyPublic(request,a,u);if(a==='surpriseVotePublicStatus')return json(request,reviewVoteStatus());return json(request,{ok:false,error:'UNKNOWN_ACTION',version:CFG.VERSION},404)}if(request.method!=='POST')return json(request,{ok:false,error:'METHOD_NOT_ALLOWED'},405);const p=await body(request),a=String(p.action||'');if(a==='createReservation')return json(request,await create(env,p));if(a==='requestStatus')return json(request,await requestStatus(env,p));if(a==='recoverReservationSession')return json(request,await recover(env,p));if(a==='reservationStatus')return json(request,await status(env,p));if(a==='cancelReservation')return json(request,await cancel(env,p));return json(request,{ok:false,error:'UNKNOWN_ACTION',version:CFG.VERSION},400)}catch(e){return json(request,{ok:false,error:String(e?.message||e),ambiguous:Boolean(e?.ambiguous),version:CFG.VERSION},Number(e?.status||500))}}};
function health(env){return{ok:true,version:CFG.VERSION,environment:CFG.ENVIRONMENT,reviewSimulation:true,reviewWritesAirwait:false,createEnabled:true,createRequiresVerifiedLiff:true,acceptedClientIds:[CFG.CHANNEL_ID],dbConfigured:Boolean(env.DB),airwaitKeyConfigured:false,lineReceptionUsesStoreOnly:true,lineReceptionOpen:'00:00',serviceMessageEnabled:false,serviceMessageReviewNote:'Service Message is not issued from the unverified Review channel.'}}
function headers(request){const o=request.headers.get('Origin')||'';const h={'Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type','Access-Control-Max-Age':'86400','Cache-Control':'no-store','Content-Type':'application/json; charset=utf-8','Vary':'Origin'};if(o===CFG.ALLOWED_ORIGIN)h['Access-Control-Allow-Origin']=o;return h}
function origin(request){if(request.headers.get('Origin')!==CFG.ALLOWED_ORIGIN)throw err('ORIGIN_NOT_ALLOWED',403)}
function preflight(request){try{origin(request);return new Response(null,{status:204,headers:headers(request)})}catch{return new Response(null,{status:403,headers:headers(request)})}}
function json(request,payload,status=200){return new Response(JSON.stringify(payload),{status,headers:headers(request)})}
async function body(request){const ct=String(request.headers.get('Content-Type')||'').toLowerCase();return ct.includes('application/json')?await request.json():Object.fromEntries(new URLSearchParams(await request.text()))}
function err(msg,status=400,ambiguous=false){const e=Error(msg);e.status=status;e.ambiguous=ambiguous;return e}
async function schema(env){await env.DB.batch([
 env.DB.prepare(`CREATE TABLE IF NOT EXISTS review_reservations(request_id TEXT PRIMARY KEY,user_hash TEXT NOT NULL,business_date TEXT NOT NULL,wait_type_id TEXT NOT NULL,receipt_no TEXT NOT NULL,reserve_id TEXT NOT NULL,adults INTEGER NOT NULL,paid_children INTEGER NOT NULL,infants INTEGER NOT NULL,state TEXT NOT NULL DEFAULT 'waiting',created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)`),
 env.DB.prepare(`CREATE INDEX IF NOT EXISTS idx_review_res_user ON review_reservations(user_hash,business_date,updated_at)`),
 env.DB.prepare(`CREATE TABLE IF NOT EXISTS review_sessions(token_hash TEXT PRIMARY KEY,user_hash TEXT NOT NULL,request_id TEXT NOT NULL,expires_at INTEGER NOT NULL,created_at INTEGER NOT NULL)`)
])}
function normalizeDate(v){const s=String(v||'').trim();return /^\d{4}-\d{2}-\d{2}$/.test(s)?s:''}
function jstDate(){const p=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()).map(x=>[x.type,x.value]));return `${p.year}-${p.month}-${p.day}`}
function reviewBusinessDay(v){const date=normalizeDate(v)||jstDate();return{ok:true,source:'review-simulation',operationalDate:date,calendarDate:date,businessType:'土日祝日',weekday:'',note:'LINE審査用テスト環境',reviewSimulation:true}}

function reviewVoteStatus(){const now=Date.now(),start=new Date(now-5*60*1000).toISOString(),end=new Date(now+60*60*1000).toISOString();return{ok:true,version:CFG.VERSION,reviewSimulation:true,mode:'voting',selected_event_id:'review-1400',event:{id:'review-1400',date:jstDate(),event_time:'14:00',vote_start:start,vote_end:end,options:[{id:'parachute',name:'パラバルーン'},{id:'treasure',name:'宝探し'},{id:'hide',name:'だるまさんが隠れた'},{id:'vault',name:'跳び箱'}]},day_events:[{id:'review-1100',event_time:'11:00',mode:'result',winner:{name:'宝探し'}},{id:'review-1400',event_time:'14:00',mode:'voting'},{id:'review-1600',event_time:'16:00',mode:'upcoming'}],daily_reset:'18:00'}}
async function proxyPublic(request,action,u){const q=new URL(CFG.DEVELOP_PUBLIC);q.searchParams.set('action',action);if(u.searchParams.get('date'))q.searchParams.set('date',u.searchParams.get('date'));q.searchParams.set('_',String(Date.now()));const r=await fetch(q,{headers:{Origin:CFG.ALLOWED_ORIGIN,Accept:'application/json'},cache:'no-store'});let d=null;try{d=await r.json()}catch{}if(!r.ok||!d)throw err('REVIEW_PUBLIC_DATA_UNAVAILABLE',503);delete d.user;return json(request,{...d,reviewProxy:true})}
function strictInt(v,min,max){let n;if(typeof v==='number')n=v;else if(typeof v==='string'&&/^(0|[1-9]\d*)$/.test(v))n=Number(v);else throw err('PEOPLE_VALIDATION_ERROR');if(!Number.isSafeInteger(n)||n<min||n>max)throw err('PEOPLE_VALIDATION_ERROR');return n}
async function verify(token){const t=String(token||'').trim();if(t.length<20)throw err('LIFF_ACCESS_TOKEN_REQUIRED',401);const q=new URL(CFG.LINE_VERIFY);q.searchParams.set('access_token',t);const vr=await fetch(q,{headers:{Accept:'application/json'},cache:'no-store'});let vd=null;try{vd=await vr.json()}catch{}if(!vr.ok||String(vd?.client_id||'')!==CFG.CHANNEL_ID||Number(vd?.expires_in||0)<=0)throw err('LIFF_TOKEN_NOT_REVIEW_CHANNEL',401);const pr=await fetch(CFG.LINE_PROFILE,{headers:{Authorization:`Bearer ${t}`,Accept:'application/json'},cache:'no-store'});let pd=null;try{pd=await pr.json()}catch{}if(!pr.ok||!pd?.userId)throw err('LINE_PROFILE_UNAVAILABLE',401);return{userId:String(pd.userId)}}
async function sha(s){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(String(s)));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function userHash(id){return sha(`${CFG.CHANNEL_ID}:${id}`)}
function requestId(v){const s=String(v||'');return /^[A-Za-z0-9_-]{8,128}$/.test(s)?s:''}
function waitType(v){const s=String(v||'');return ALLOWED_WAIT.has(s)?s:''}
async function create(env,p){const id=requestId(p.requestId);if(!id)throw err('REQUEST_ID_REQUIRED');const line=await verify(p.liffAccessToken),uh=await userHash(line.userId);const adults=strictInt(p.adults,1,10),children=strictInt(p.paidChildren,0,10),infants=strictInt(p.infants,0,10);const total=adults+children+infants;if(total>10||children+infants>adults*3)throw err('PEOPLE_VALIDATION_ERROR');const wt=waitType(p.waitTypeId);if(!wt)throw err('WAIT_TYPE_NOT_ALLOWED_FOR_REVIEW');const date=normalizeDate(p.operationalDate)||jstDate();const old=await env.DB.prepare('SELECT * FROM review_reservations WHERE request_id=? LIMIT 1').bind(id).first();if(old){if(old.user_hash!==uh)throw err('REQUEST_OWNER_MISMATCH',403);return publicReservation(old,true)}const same=await env.DB.prepare("SELECT * FROM review_reservations WHERE user_hash=? AND business_date=? AND state<>'canceled' ORDER BY updated_at DESC LIMIT 1").bind(uh,date).first();if(same)return publicReservation(same,true);const now=Date.now();const suffix=String(now%100000).padStart(5,'0'),receipt='9'+suffix,reserve='9'+String(now).slice(-11).padStart(11,'0');const ins=await env.DB.prepare(`INSERT OR IGNORE INTO review_reservations(request_id,user_hash,business_date,wait_type_id,receipt_no,reserve_id,adults,paid_children,infants,state,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,'waiting',?,?)`).bind(id,uh,date,wt,receipt,reserve,adults,children,infants,now,now).run();if(Number(ins?.meta?.changes||0)!==1){const raced=await env.DB.prepare('SELECT * FROM review_reservations WHERE request_id=? LIMIT 1').bind(id).first();if(raced)return publicReservation(raced,true);throw err('REVIEW_CREATE_RACE',409,true)}const row=await env.DB.prepare('SELECT * FROM review_reservations WHERE request_id=? LIMIT 1').bind(id).first();return publicReservation(row,false)}
function publicReservation(r,alreadyExists=false){return{ok:true,stored:true,alreadyExists,reviewSimulation:true,notificationReady:false,receiptNo:String(r.receipt_no),reserveId:String(r.reserve_id),businessDate:String(r.business_date),operationalDate:String(r.business_date),waitTypeId:String(r.wait_type_id),requestId:String(r.request_id),version:CFG.VERSION}}
async function requestStatus(env,p){const id=requestId(p.requestId);if(!id)throw err('REQUEST_ID_REQUIRED');const line=await verify(p.liffAccessToken),uh=await userHash(line.userId),r=await env.DB.prepare('SELECT * FROM review_reservations WHERE request_id=? LIMIT 1').bind(id).first();if(!r)return{ok:true,found:false,requestId:id,version:CFG.VERSION};if(r.user_hash!==uh)throw err('REQUEST_OWNER_MISMATCH',403);return{...publicReservation(r,true),found:true}}
async function recover(env,p){const line=await verify(p.liffAccessToken),uh=await userHash(line.userId),date=normalizeDate(p.businessDate)||jstDate();const r=await env.DB.prepare('SELECT * FROM review_reservations WHERE user_hash=? AND business_date=? ORDER BY updated_at DESC LIMIT 1').bind(uh,date).first();if(!r)return{ok:true,found:false,reviewSimulation:true,version:CFG.VERSION};const raw=crypto.randomUUID().replace(/-/g,'')+crypto.randomUUID().replace(/-/g,''),th=await sha(raw),now=Date.now(),expires=now+CFG.SESSION_TTL_MS;await env.DB.prepare('INSERT OR REPLACE INTO review_sessions(token_hash,user_hash,request_id,expires_at,created_at) VALUES(?,?,?,?,?)').bind(th,uh,r.request_id,expires,now).run();return{ok:true,found:true,reviewSimulation:true,sessionToken:raw,businessDate:r.business_date,receiptNo:r.receipt_no,waitTypeId:r.wait_type_id,expiresAt:expires,version:CFG.VERSION}}
async function sessionRow(env,raw){const t=String(raw||'').trim();if(t.length<32)throw err('SESSION_REQUIRED',401);const h=await sha(t),s=await env.DB.prepare('SELECT * FROM review_sessions WHERE token_hash=? LIMIT 1').bind(h).first();if(!s||Number(s.expires_at||0)<=Date.now())throw err('SESSION_EXPIRED',401);const r=await env.DB.prepare('SELECT * FROM review_reservations WHERE request_id=? LIMIT 1').bind(s.request_id).first();if(!r)throw err('RESERVATION_NOT_FOUND',404);return{s,r}}
async function status(env,p){const {r}=await sessionRow(env,p.sessionToken);const elapsed=Date.now()-Number(r.created_at||0);let state=String(r.state||'waiting');let ahead=3;if(state!=='canceled'){if(elapsed>=90000)state='done';else if(elapsed>=12000)state='calling';else if(elapsed>=6000)ahead=1}const active=state==='waiting'||state==='calling';return{ok:true,found:true,reviewSimulation:true,businessDate:r.business_date,receiptNo:r.receipt_no,reserveId:r.reserve_id,waitTypeId:r.wait_type_id,waitTypeName:(WAIT_TYPES.find(x=>x.waitTypeId===r.wait_type_id)||{}).waitTypeName||'審査用受付',state,status:state,isCalling:state==='calling',aheadCount:active?ahead:null,queueRank:active?ahead+1:null,activeCount:active?Math.max(4,ahead+1):0,checkedAt:Date.now(),version:CFG.VERSION}}
async function cancel(env,p){const line=await verify(p.liffAccessToken),uh=await userHash(line.userId),{s,r}=await sessionRow(env,p.sessionToken);if(s.user_hash!==uh||r.user_hash!==uh)throw err('SESSION_OWNER_MISMATCH',403);await env.DB.prepare("UPDATE review_reservations SET state='canceled',updated_at=? WHERE request_id=?").bind(Date.now(),r.request_id).run();return{ok:true,canceled:true,reviewSimulation:true,businessDate:r.business_date,receiptNo:r.receipt_no,reserveId:r.reserve_id,waitTypeId:r.wait_type_id,state:'canceled',version:CFG.VERSION}}

export const __reviewTest=Object.freeze({
  health,strictInt,waitType,reviewBusinessDay,reviewVoteStatus,
  channelId:CFG.CHANNEL_ID,waitTypes:WAIT_TYPES
});
